### ISSUE TITLE
Раздел активные заявки. Все кнопки должны стать кликабельными и выводить соответсующие модалки в соответсвии с дизайном и Брифом (кроме чата)

### ISSUE THREAD

**Issue by ArturKaramov** [ya-pomogau/frontend#103]
Раздел активные заявки. Все кнопки должны стать кликабельными и выводить соответсующие модалки в соответсвии с дизайном и Брифом (кроме чата).

**Comment by kspshnik** [comment]
А что это за issue? %)

**Comment by ArturKaramov** [comment]
> А что это за issue? %)

что-то не так?) разбираюсь как прикрепить задачу на доску задач

**Comment by kspshnik** [comment]
Все issues, у которых задан проект, попадают на доску автоматом.
![2023-12-26_23-05](https://github.com/ya-pomogau/frontend/assets/11374004/5aa02470-1e08-4bf2-86ae-d0cc4e3cb8b9)
