### ISSUE TITLE
Механика работы с картой

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#132]
Нужно проверить компонента карты и сделать его универсальной для волонтера и реципиента

**Comment by ArturKaramov** [comment]
@INextYP 
Привет! подскажи плиз как лучше поступить: ответвиться от волонтеров и смерджить туда реципиентов? тогда куда потом делать пулл реквест? в ветку волонтеров?)

**Comment by INextYP** [comment]
> @INextYP 
> Привет! подскажи плиз как лучше поступить: ответвиться от волонтеров и смерджить туда реципиентов? тогда куда потом делать пулл реквест? в ветку волонтеров?)

Карта - универсальный инструмент. Ты можешь создать ветку от волонтёра или реципиента, без разницы, тебе всё-равно делать объединение. А PR потом нужно делать в Develop.

**Comment by INextYP** [comment]
Done.
