### ISSUE TITLE
Доработка функционала администратора

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#161]
Что требуется:
- [x] Развернуть и запустить у себя локально бекенд;
- [x] Создать ручками Главного администратора (@kspshnik напиши плз мини-гайд, как его создать);
- [x] Настроить логин администратора через логин и пароль (страница `pages/login`). Должно быть полное взаимодействие с бекендом;
- [x] При переходе на раздел "Блокировка/ подтверждение" в зависимости от выбранного таба с бекенда должны запрашиваться пользователи той или иной роли с соответствующим статусом. Требуется написать слайсы в Redux Toolkit Query на получение пользователей.
- [x] У администратора должен заработать функционал подтверждения волонтеров и реципиентов (функционал подтверждения главным администратором обычного администратора не в приоритете, но если время будет, то можно и его запилить)(блокировку и выдачу ключей пока не включаем).

Все ручки находятся на бекенде в папке `API`.

**Comment by kspshnik** [comment]
@INextYP и все-все-все :), для изготовления :) главного администратора надо создать администратора стандартным путём, и затем с помощью Compass вручную в базе проставить ему поля `isActive` и `isRoot` в `true`.

**Comment by kspshnik** [comment]
@marussia1996 проставь пожалуйста assignees на нужное количество товарищей :)
