### ISSUE TITLE
Feature: добавить обработку ошибок приходящих с сервера на запросы для волонтеров, реципиентов, админов.

### ISSUE THREAD

**Issue by marussia1996** [ya-pomogau/frontend#172]
Например, при нажатии на подтверждение бессрочной заявки, у которой нет волонтера возвращается ошибка 403, необходимо как минимум не выполнять перекрашивание галочки и воскл. знака в серый и показать попап с ошибкой ("Вы не можете подтвердить выполнение пока волонтер не откликнулся на заявку") или же добавить условие, что бессрочная заявка пока не имеет волонтера не имеет и кнопок подтверждения и конфликта.

**Comment by AlexandrGerasimov63** [comment]
@Anton-Laid ты себе забрал эту задачу? а то у тебя про кнопку есть пунктик =)

**Comment by Anton-Laid** [comment]
> @Anton-Laid ты себе забрал эту задачу? а то у тебя про кнопку есть пунктик =)

Я взял задачи по админке

**Comment by AlexandrGerasimov63** [comment]
@Anton-Laid А это свободно получается?
![2024-03-13_15-20-52](https://github.com/ya-pomogau/frontend/assets/97280804/16afecd6-ce8c-48c9-a61c-6fc9278115a4)
![2024-03-13_15-20-21](https://github.com/ya-pomogau/frontend/assets/97280804/8c005bed-198c-477c-9cf4-8311941cc238)
