### ISSUE TITLE
Проверка верстки чатов + storybook (волонтер + реципиент)

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#188]
В рамках задачи нужно проверить верстку чатов (включая мобильное разрешение) для реципиента и волонтера + добавить истории в Storybook.

:exclamation: Важно: логику не проверяем. В большей степени там будет изменяться работа с компонентом.

Все баги, а также предложения по коду указываем в комментариях к этой задаче. Правки в коде сейчас не делаем (можно делать для себя некий playground, который не будет никуда пушиться, а просто удалиться после окончания работы с задачей)

Ветка, где смотрим: `develop`.

Путь до текущей верстки: `src/entities/chat/ui/chat/*`

Макет: 
- [волонтер](https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=6718-13644&t=Y58PcVgYSmx99emh-4)
- [реципиент](https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=555-7419&t=Y58PcVgYSmx99emh-4)

**Comment by Anton-Laid** [comment]
### Проверка чатов у волонтера и реципиента. 
- Изначально у авторизованных пользователей чат не открывается, нужно в `header` в `DropDownMenu` перекинуть переменную `hendleChat` и тогда все заработает.
- Верстка на 1440px не совпадает с макетом, компонент меньше. 
![Снимок 01 06 2024 в 14 26](https://github.com/ya-pomogau/frontend/assets/113182938/de81578f-2455-422a-a106-c0044cae3238)
- Чат адаптируется под разные разрешения экрана, верстка не ломается. 
- Для мобильного экрана нужно подредактировать верстку 
![Снимок 01 06 2024 в 14 34](https://github.com/ya-pomogau/frontend/assets/113182938/e80de231-85b3-422a-86f2-dc92a6c6f45f)
- В Storybook есть данный компонент, все настраивается и все данные можно проверить. 
- Работает кнопка по прикреплению файлов, но в чате нет отображения что мы прикрепили файл к сообщению. 
![Снимок 01 06 2024 в 14 40](https://github.com/ya-pomogau/frontend/assets/113182938/0268b093-ee43-4622-93e4-e3905683ec26)

**Comment by INextYP** [comment]
`Верстка на 1440px не совпадает с макетом, компонент меньше.` - а можешь показать в дизайне, где такой вариант чата? Увидел только 586x374

**Comment by INextYP** [comment]
`Изначально у авторизованных пользователей чат не открывается, нужно в header в DropDownMenu перекинуть переменную hendleChat и тогда все заработает` - а на самой таске проверял работу? Или там вообще нет такого функционала?
