### ISSUE TITLE
Проверка верстки чатов + storybook (администратор)

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#190]
В рамках задачи нужно проверить верстку чатов (включая мобильное разрешение) для страницы администратора + добавить историю в Storybook.

:exclamation: Важно: логику не проверяем. В большей степени там будет изменяться работа с компонентом.

Все баги, а также предложения по коду указываем в комментариях к этой задаче. Правки в коде сейчас не делаем (можно делать для себя некий playground, который не будет никуда пушиться, а просто удалиться после окончания работы с задачей)

Ветка, где смотрим: `develop`.

Макет: 
- [чат администратора](https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=1537-18236&t=Y58PcVgYSmx99emh-4)

**Comment by Anton-Laid** [comment]
"Взялся за эту задачу, потому что новички, возможно, не знают, как заходить в админку и какие параметры нужны в таске, чтобы она высвечивалась в конфликтах.

На данный момент присутствуют страницы "Конфликты" и "Конфликт в работе", так как нужно было успеть сделать для MVP. 

### Чат:

- добавить вкладку "Жду ответа" и сопоставить с вкладками подходящий функционал (раньше мы его урезали).
- логика с открытием и закрытием чата и окна конфликта работает корректно.
- список чатов и окно для чата можно увеличить.
![Снимок экрана 2024-06-02 в 15 48 29](https://github.com/ya-pomogau/frontend/assets/113182938/10977bc0-91eb-4cf1-ba5f-c6b05eb2bd97)
- в чатах нет функционала по закреплению файлов и фото в чате (компоненты не сверстаны)
![5B6C3429-BD27-4E49-AB6C-D1BD58F3F8E4_4_5005_c](https://github.com/ya-pomogau/frontend/assets/113182938/663ab6e8-86dd-4bc3-8da3-be789dc39671)
**конфликты**
- кнопка для телефона работает 
![Снимок 02 06 2024 в 15 54](https://github.com/ya-pomogau/frontend/assets/113182938/51f2fd4a-a35f-44b0-8df5-e0310e01ac6e)
- есть адаптив под разные разрешения экранов
![Снимок 02 06 2024 в 15 55](https://github.com/ya-pomogau/frontend/assets/113182938/6a615ce4-bca4-42d0-8f9c-bee3cbf7d744)
- адаптив под телефон есть и работает хорошо
![Снимок 02 06 2024 в 15 58](https://github.com/ya-pomogau/frontend/assets/113182938/692d972e-dc70-49f0-90d2-b47272913bbc)
- в меню кнопка чата присутствует и работает
![Снимок 02 06 2024 в 16 01](https://github.com/ya-pomogau/frontend/assets/113182938/f9dce48d-a4fd-45d8-a800-e7e4dda1ef5a)
- сейчас по функционалу можно из раздела "Конфликты", благодаря кнопке "Взять в работу", переместить конфликт в "Конфликт в работе", а затем нажать на кнопку "Разрешить конфликт" и таска удалится из базы."
### storybook
- MessageCard выдает ошибку
- Message работает корректно
- ConflictCard работает и можно настроить под себя 
![E120FC8F-0CD5-4F55-980F-E9F07FD0CBC0](https://github.com/ya-pomogau/frontend/assets/113182938/b4ea3cd4-c145-487b-a640-0d4e4cb457e4)
- PopupChat есть и работает
- Submenu для чатов есть и работает

**Comment by ArtPsycho** [comment]
Мне тогда другую задачу брать под себя?

**Comment by INextYP** [comment]
> Мне тогда другую задачу брать под себя?

Нет. Антон распишет, как зайти в админку. Зайди и также просмотри функционал, описанный в карточке. 
Как это всё должно работать описано в брифе проекта.
Если есть вопросы ты можешь смело задавать их в чате.

**Comment by ArtPsycho** [comment]
- При разрешении экрана 320 пикселей в ширину, наименование ролей участников заезжают на аватары. Тоже самое и при  разрешении в 375px в ширину

![Image](https://github.com/ya-pomogau/frontend/assets/62343148/ce3802a8-310a-49aa-93fd-9bf0c7249c85)

- Попап номера телефона уходит за экран

![Image](https://github.com/ya-pomogau/frontend/assets/62343148/536f057c-f88f-45eb-8b5f-68d903565b4c)

- Можно увеличить ширину чатов  и уменьшить высоту заголовка раздела на мобилке

![Image](https://github.com/ya-pomogau/frontend/assets/62343148/ad72ce1d-d31e-4a23-8652-dfd2a9774173)

- Уменьшить размеры заголовка блока и высоту самого блока

![Image](https://github.com/ya-pomogau/frontend/assets/62343148/ddde63b8-e02a-4a53-8594-c82f1026102c)

**Comment by INextYP** [comment]
`список чатов и окно для чата можно увеличить.` - это по дизайну или личное предложение по улучшению? @Anton-Laid

**Comment by INextYP** [comment]
@Anton-Laid Чат между пользователем и админом (который в разделе "Ждут ответа") имеется?

**Comment by ArtPsycho** [comment]
> `список чатов и окно для чата можно увеличить.` - это по дизайну или личное предложение по улучшению? @Anton-Laid 

По дизайну во всю ширину![Screenshot_20240605-101452.png](https://github.com/ya-pomogau/frontend/assets/62343148/c5646194-36bb-4377-b563-af2325467c51)

**Comment by Anton-Laid** [comment]
@INextYP 
Первый вопрос:  по макету надо увеличить окно, оно должно быть в ровень с шапкой "чат"
Второй вопрос: он был, но я потом его убрал, так как нам надо было показать заказчику готовую админку, а переписываться они могли только через "ВК" и вкладку «Ждут ответа» я убрал. 
Что указал @ArtPsycho тоже нужно будет поправить, все правильно подметил.
