### ISSUE TITLE
Проверка верстки компонента "меню" + storybook

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#191]
В рамках задачи нужно проверить верстку dropdown меню + добавить истории в Storybook.

![Image](https://github.com/ya-pomogau/frontend/assets/70805943/d85458a7-1b75-4beb-88f9-b539c3e87351)

![Image](https://github.com/ya-pomogau/frontend/assets/70805943/a0480527-d661-4795-b765-602ae9ceb8ab)

![Image](https://github.com/ya-pomogau/frontend/assets/70805943/8d124d52-09ba-4e82-81d1-febc4e4286bf)

:exclamation: Важно: у роли Реципиент и Волонтер в меню есть кнопка "Связь с администратором", а у Администратора данной кнопки быть не должно. Если не совпадает - обязательно указать в комментариях к карточке задачи.

Все баги, а также предложения по коду указываем в комментариях к этой задаче. Правки в коде сейчас не делаем (можно делать для себя некий playground, который не будет никуда пушиться, а просто удалиться после окончания работы с задачей)

Ветка, где смотрим: `develop`.

Макет: 
- [Декстопное разрешение](https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=2420-14243&t=SMACwhDf9FmCl8RJ-4)
- [Мобильное разрешение](https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=7058-22153&t=SMACwhDf9FmCl8RJ-4)

**Comment by LodeNik23** [comment]
Десктопная версия(Ширина >900px).

**Без входа**
Отсутствует.

**Под админом:**
Выпадающее меню включает в себя: 
"Написать администратору"(По ТЗ его быть не должно)-не работает и "выход"-работает. 
Нет состояния "hover" при наведении. В фигме тоже нет.
Лишний отступ под последней строкой меню - в фигме гораздо меньше.
Располагается выше черты-отбивки шапки. В фигме чуть ниже.

**Под vk юзером:** 
Выпадающее меню включает в себя "Написать администратору"-не работает и "выход"-работает. 
Нет состояния "hover" при наведении. В фигме тоже нет.
Лишний отступ под последней строкой меню - в фигме гораздо меньше.
Располагается выше черты-отбивки шапки. В фигме чуть ниже.


Мобильная версия(Ширина<900px).

**Без входа**
Неотцентрованная кнопка "Войти через Вконтакте" - работает.В консоли страшное сообщение "Внимание-вниманиеЭто важно, чёрт возьми! Ни в коем случае не копируйте и не вставляйте что‑либо сюда, вы рискуете потерять доступ к своему аккаунту.Ввод информации сюда может дать злоумышленникам доступ к вашему аккаунту VK ID"... Но я уже раз пять зашел под вк профилем... Спасибо, мне не хватало стресса.

**Под vk юзером:**
Всплывающее окно находится слишком низко. В фигме располагается примерно в 2-3px от черты-отбивки шапки сайта.
Не тот порядок - в фигме: Блог, Личный кабинет, Политика конфиденциальности, Контакты,Выйти. По факту: 
"Написать администратору"-клик ничего не делает. Клик по синему полю совершает выход из учетной записи.
"Личный кабинет" -клик переход на карту http://localhost:3000/profile/map с оповещением "Спасибо за регистрацию. Как только администратор подтвердит Вашу учетную запись, Вы сможете откликаться на заявки". 
"Блог" -клик -переход на пустую страницу http://localhost:3000/blog. Ховер-подчеркивание очень широкое.
"Политика конфиденциальности" -клик-переход на заполненную http://localhost:3000/policy.
"Контакты" -клик-переход на заполненную http://localhost:3000/contacts.
"Выход"-работает.
При ширине меньше 275px всплывающее меню уходит за экран и два пункта обрезаются.  
Лишний отступ под последней стройкой меню - в фигме меньше.

**Под админом:**
Всплывающее окно находится слишком низко. В фигме располагается примерно в 2-3px от черты-отбивки шапки сайта.
Не тот порядок - в фигме: Блог, Личный кабинет, Политика конфиденциальности, Контакты,Выйти. По факту: 
"Написать администратору"-клик ничего не делает. Клик по синему полю совершает выход из учетной записи.
"Личный кабинет" -клик переход на карту http://localhost:3000/profile/map с оповещением "Спасибо за регистрацию. Как только администратор подтвердит Вашу учетную запись, Вы сможете откликаться на заявки". 
"Блог" -клик -переход на пустую страницу http://localhost:3000/blog. Ховер-подчеркивание очень широкое.
"Политика конфиденциальности" -клик-переход на заполненную http://localhost:3000/policy.
"Контакты" -клик-переход на заполненную http://localhost:3000/contacts.
"Чат" - клик-переход на заполненную страницу http://localhost:3000/chat
"Выход"-работает.
При ширине меньше 275px всплывающее меню уходит за экран и два пункта обрезаются.  
Лишний отступ под последней стройкой меню - в фигме меньше.


В сторис в режиме мобильном меню состоит из 4х пунктов - Личный кабинет, Блог, Политика конфиденциальности, Контакты. Длинные пункты не складываются в 2 строки(нужно ли?). После клика на пункт ховер перекрывается чертой во всю длину экрана(откуда такое поведение?)
Ховер при наведении работает корректно.
В режиме десктопа в сторис отсутствует кнопка меню и выпадающее окно.

**Comment by INextYP** [comment]
Задача выполнена
