### ISSUE TITLE
Проверить раздел политика конфиденциальности (редактирование, вывод)

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#192]
В рамках задачи требуется проверить работу политики конфиденциальности. Описать:
- каким образом она выводится в текущем приложении;
- есть ли возможность редактирования у главного администратора;
- проверить верстку в целом;

Важно:
Политика конфиденциальности выглядит единым образом для неавторизованных пользователей, волонтеров, реципиентов и администраторов, но только главный администратор может редактировать её. Обязательно нужно проверить этот кейс.

Ветка, где проверяем: `develop`;

Правки никакие не пушим. Задачи по исправлению ошибок/ доработкам будут в следующем спринте.

Все баги, предложения и т.д. указываем в комментариях к этой карточки

**Comment by LatyshevDD** [comment]
![Image](https://github.com/ya-pomogau/frontend/assets/110352990/778831c3-af92-40ef-a807-3d31c11e5578)

В разметке используется обертка с высотой 90vh. В будущем это может привести к проблемам отображения страницы в мобильных браузерах, будет появляться вертикальный скролл. Предлагаю дополнить проект возможностью расчета vh на основе информации из window.InnerHeight. Могу сделать.

**Comment by LatyshevDD** [comment]
![Image](https://github.com/ya-pomogau/frontend/assets/110352990/cfa32f1f-8b8b-43f2-b208-88a94466e1d9)
![Image](https://github.com/ya-pomogau/frontend/assets/110352990/f5ffb1ce-143f-4a8b-85bb-891da92197c1)

В админке нет возможности редактирования тектовых полей политики конфиденциальности

**Comment by LatyshevDD** [comment]
С версткой все в порядке

**Comment by LatyshevDD** [comment]
Я же правильно понял что главный администратор это role "Admin" в Redux?

**Comment by marussia1996** [comment]
> Я же правильно понял что главный администратор это role "Admin" в Redux?



> Я же правильно понял что главный администратор это role "Admin" в Redux?

Admin это любой администратор главным администратором является тот у кого в поле isRoot: true

**Comment by LatyshevDD** [comment]
Понял. Спасибо!

**Comment by LatyshevDD** [comment]
И еще верстка на мобильной версии не соответсвует макету.
Отсутствует часть элементов и неправильно установлены отступы.


![Image](https://github.com/ya-pomogau/frontend/assets/110352990/71b00257-43e7-494a-aa5c-a7e60e154328)
![Image](https://github.com/ya-pomogau/frontend/assets/110352990/f456e613-bd83-4f3d-8a3f-5e3b5b73cdc5)

**Comment by kspshnik** [comment]
Проверка выполнена
