### ISSUE TITLE
Проверить раздел "Контакты" (редактирование, вывод)

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#193]
В рамках задачи требуется проверить работу раздела "Контакты". 
Описать:
- каким образом они выводится в текущем приложении (если данные сейчас статичны, т.е. не приходят с бекенда - обязательно указать в комментариях к карточке);
- проверить верстку в целом (мобилка + декстоп);

Важно:
Контакты выглядят единым образом для неавторизованных пользователей, волонтеров, реципиентов и администраторов, но только Главный администратор может менять их. Обязательно нужно проверить этот кейс.

Правки никакие не пушим. Задачи по исправлению ошибок/ доработкам будут в следующем спринте.

Ветка, где проверяем: `develop`;

Все баги, предложения и т.д. указываем в комментариях к этой карточки

**Comment by IvannaBalanyuk** [comment]
Данные о контактах сейчас статичны:


![Image](https://github.com/ya-pomogau/frontend/assets/124444858/75a3523c-a0d9-4c31-a377-fec385673e7d)

При сохранении формы после редактирования никуда не уходят:


![Image](https://github.com/ya-pomogau/frontend/assets/124444858/a40e881e-dd11-4b74-a6a4-d766d6483c83)

Network тоже проверяла - после сохранения никакой запрос не уходит.

**Comment by IvannaBalanyuk** [comment]
Процесс редактирования на фронте возможно нуждается в доработке. Сейчас оба блока используют один коллбэк `handleEnableEdit` и поэтому после нажатия `Изменить данные` в одном поле редактирование открывается и для второго тоже.

**Comment by IvannaBalanyuk** [comment]
Возможность редактирования контактов открыта для пользователя с ролью `Admin` с нужными разрешениями:


![Image](https://github.com/ya-pomogau/frontend/assets/124444858/dc95560b-d88b-4b89-b39d-b30610be9d24)



![Image](https://github.com/ya-pomogau/frontend/assets/124444858/b86fc792-aa71-41d8-acfe-26f2523a0cb0)

У нашего тестового admin4 в permissions пусто, поэтому для проверки вёрстки "выключала" `roleChecker`.

**Comment by IvannaBalanyuk** [comment]
**По верстке - много расхождений с макетом.**
В первую очередь обратил на себя внимание header (компонент `SmartHeader`), но это за рамками таски, поэтому рассказываю в предпоследнем комменте)

**Начну с десктопа.**
Блоки с контактами сверстаны с использованием множества margin-отступов. В паре мест нижний margin одного блока и верхний другого схлопываются, из-за чего в итоге отступы не соответствуют макету.

Вот такие отступы в макете:


![Image](https://github.com/ya-pomogau/frontend/assets/124444858/d0fe39b1-cb0b-47bd-94e4-0594e9b7f780)

А так сейчас выглядит верстка:


![Image](https://github.com/ya-pomogau/frontend/assets/124444858/5025d27e-7dc8-4e0d-ae03-f5e3a8029553)

"Потерянные" расстояния:


![Image](https://github.com/ya-pomogau/frontend/assets/124444858/14ec6f40-a558-48f5-b763-d80fe5212084)



Для form написаны стили, но не подключены:


![Image](https://github.com/ya-pomogau/frontend/assets/124444858/c39084cc-6f84-4593-b921-1173e611b207)

**Comment by IvannaBalanyuk** [comment]
Тексту `Изменить данные` нужно добавить стили (сейчас всё, кроме цвета, по дефолту):


![Image](https://github.com/ya-pomogau/frontend/assets/124444858/c83bf11b-07c3-4346-95bb-8a2916fdbcfc)



Сейчас вот так:



![Image](https://github.com/ya-pomogau/frontend/assets/124444858/c6ac4f87-685c-4a75-9730-5e64e5fdcc08)



А надо так:



![Image](https://github.com/ya-pomogau/frontend/assets/124444858/54809b3d-de8e-4606-9a32-3e641248ac91)

**Comment by IvannaBalanyuk** [comment]
Предлагаемая верстка:


![Image](https://github.com/ya-pomogau/frontend/assets/124444858/a2774ee7-cab5-4cb2-ac33-35e8a177c9b3)



![Image](https://github.com/ya-pomogau/frontend/assets/124444858/0db7d727-3752-4df7-8589-052061682828)



![Image](https://github.com/ya-pomogau/frontend/assets/124444858/c51d3eee-419a-4f69-8f05-8998082dff33)

**Comment by IvannaBalanyuk** [comment]
В стили вносила следующие изменения (в песочнице):


![Image](https://github.com/ya-pomogau/frontend/assets/124444858/b7fd710f-573d-48f7-8d89-e7ad9431d7b8)
![Image](https://github.com/ya-pomogau/frontend/assets/124444858/8e738d93-e8ff-4490-acc1-1eaaf01ced75)
![Image](https://github.com/ya-pomogau/frontend/assets/124444858/0e53719d-1ca3-4c65-ac4e-b51fca0ffbcc)
![Image](https://github.com/ya-pomogau/frontend/assets/124444858/31eb1caa-0b06-4779-bce7-ccef3a40fd09)

В последнем - добавила gap, чтобы отступы задавал контейнер.

**Comment by IvannaBalanyuk** [comment]
Про `SmartHeader`. У этого компонента высота на `10px` больше, чем в макете, + паддинги не те. Из-за этого контент компонента расположен со смещением вверх от центра (в макете контент центрирован по вертикали) + сам блок вылезает вниз визуально (ощущение, что по задумке нижняя граница `SmartHeader` должна находиться на одном уровне с верхней границей цветастого блока с данными юзера):


![Image](https://github.com/ya-pomogau/frontend/assets/124444858/4aa30318-ac0c-4aad-bdd8-73fbac6e0405)

Вот так в макете:



![Image](https://github.com/ya-pomogau/frontend/assets/124444858/d5364b3d-662f-4c9d-9cf9-2a0eaf3be6bf)

В мобильной версии проблема с высотой `SmartHeader` выражена ещё ярче - в макете `60px`, а в верстке сейчас всё те же `100px`. Скрины про мобилку - в следующем комментарии.

**Comment by IvannaBalanyuk** [comment]
В мобилке по верстке все те же проблемы, что и в десктопе. Дополнительно - в мобильной версии блок `Изменить данные` по макету находится вовне блока с данными (видно по расположению бордера). В целом медиа-запросов в стилях нет, т.е. адаптив как таковой, видимо, не реализовывался.

Так в макете:



![Image](https://github.com/ya-pomogau/frontend/assets/124444858/3db636a8-65c8-4a87-a788-b1ba59248854)

Так сверстано сейчас:


![Image](https://github.com/ya-pomogau/frontend/assets/124444858/46146270-e01f-4edc-8875-77355fff3bfe)
![Image](https://github.com/ya-pomogau/frontend/assets/124444858/e7494928-b22e-423e-af82-c596cf4c618c)

**Comment by IvannaBalanyuk** [comment]
Также не реализовано предусмотренное макетом отображение элементов в процессе редактирования - кнопка `Изменить данные` для редактируемого поля не отображается, цвет текста редактируемого поля меняется на черный, второе поле остается без изменений.


![Image](https://github.com/ya-pomogau/frontend/assets/124444858/5ae94d4c-2183-4120-b962-03e2970c9b50)

**Comment by kspshnik** [comment]
> У нашего тестового admin4 в permissions пусто, поэтому для проверки "выключала" roleChecker.


Кстати, здорово ещё убедиться, что `usePermission()` грамотно реагирует на `role === UserRole.ADMIN && isRoot === true`, выдавая _все_ права, т.к. суперпользователь (root, главный администратор) по определению может всё и не видит преград :)

**Comment by IvannaBalanyuk** [comment]
>  Кстати, здорово ещё убедиться, что usePermission() грамотно реагирует на role === UserRole.ADMIN && isRoot === true, выдавая все права

Т.е. вот тут в массиве


![Image](https://github.com/ya-pomogau/frontend/assets/124444858/f553e1a1-ac74-4bbb-92cb-84798b4bfe1b)

Должны быть перечислены все разрешения, предусмотренные для всемогущего?  В `CreateAdminDto` содержатся такие:



![Image](https://github.com/ya-pomogau/frontend/assets/124444858/0b5ae2f9-ce76-4ce5-8a36-97023e39f438)



![Image](https://github.com/ya-pomogau/frontend/assets/124444858/787843f5-11d4-4527-8c0b-d73907a58d86)


Значит в массив должны попасть следующие элементы:


![Image](https://github.com/ya-pomogau/frontend/assets/124444858/eda4d9fe-d82c-478a-8f2b-8639fa9835dc)

Работа `usePermission()`  действительно вызывает вопросы в контексте данного кейса. Хук сверяет переданный ему массив разрешений с разрешениями в `user.data.permissions` . И сейчас хук вернёт положительный результат в случае, если хотя бы один элемент совпадет:


![Image](https://github.com/ya-pomogau/frontend/assets/124444858/983708fc-90d1-455a-b83a-c0c2f3a005c5)

А к редактированию контактов можно допускать (если я теперь  всё правильно поняла) только Главного администратора, а это такой, у которого есть ВСЕ разрешения.

Проверки на `isRoot === true`  в хуке нет.

Т.е. в хук нужно добавить проверку на `isRoot === true` и в случае успеха возвращать `isAllowed === true` (нужна ли тогда сверка разрешений на предмет "есть ВСЕ"?).

**Comment by kspshnik** [comment]
> А к редактированию контактов можно допускать (если я теперь всё правильно поняла) только Главного администратора, а это такой, у которого есть ВСЕ разрешения.
> 


Не совсем ;)
Рута допускаем **ВООБЩЕ КО ВСЕМУ** без дополнительных проверок, остальных - если есть права ;)

> Проверки на `isRoot === true` в хуке нет.
> 
> Т.е. в хук нужно добавить проверку на `isRoot === true` и в случае успеха возвращать `isAllowed === true` (нужна ли тогда сверка разрешений на предмет "есть ВСЕ"?).

Да ;) И руту, ес-сно, больше ничего проверять нинада - Главный администратор может _всё_ ;)

**Comment by INextYP** [comment]
Отличная работа, умничка :)

**Comment by kspshnik** [comment]
Проверка выполнена
