### ISSUE TITLE
Проверить редактирование данных пользователя (верстка + функционал)

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#194]
![Image](https://github.com/ya-pomogau/frontend/assets/70805943/93c6d2ea-b176-423d-b132-8758c6889b0d)

Проверяем работу по брифу:
- Заходим в личный кабинет
- Нажимаем кнопку “⚙ Настройки”
- Всплывает окно настроек личной карточки
- Меняем фото, ФИО, телефон, адрес
-- Нажимаем кнопку “Сохранить”. Окно настроек закрывается, данные в ЛК обновляются
-- Нажимаем кнопку “✖”. Окно настроек закрывается, данные в ЛК остаются без изменений.

Проверяем верстку по макету (декстоп + мобилка).

Обязательно смотрим, подключен ли реальный бекенд или используются моковые данные.

Все баги/ несовпадения и предложения указывайте в комментариях к этой карточке.

**Comment by AlexeyKrutyakov** [comment]
после входа в личный кабинет и нажатия кнопки "Настройки" всплывает окно настроек личной карточки

- не работает кнопка "Изменить фото"
- после изменения любово из оставшихся полей (имя, телефон, адрес) выбрасывается ошибка, после перезагрузки страницы ошибка исчезает, данные в б.д. корректно изменяются (если зайти значала в меню "Контакты", такая проблема не возникает)
скрин ошибки:
<img width="1001" alt="Screenshot 2024-06-02 at 23 02 05" src="https://github.com/ya-pomogau/frontend/assets/11219356/af9a6ef4-d2e3-4c3a-b07f-436b9f15e60c">

- в поле ввода номера телефона можно внести любые символы, данные принимаются, сохраняются
- в поле ввода имени можно ввести только цифры, данные принимаются, сохраняются

бекенд подключен, моковые данные не используются
вёрстку проверить пока не успел

**Comment by AlexeyKrutyakov** [comment]
- Нажимаем кнопку “✖”. Окно настроек закрывается, данные в ЛК остаются без изменений.

Отличия в десктоп версии по вёрстке:

- карточка личной информации:


![Image](https://github.com/ya-pomogau/frontend/assets/11219356/b3913400-9cd5-4196-aeaf-b1a58df7a245)


- всплывающее окно редактирования личной информации:
размер окна отличается от макета, элементы смещены относительно макета


![Image](https://github.com/ya-pomogau/frontend/assets/11219356/a464b65f-bc6a-4841-b616-9456229c6374)


Мобильная версия:
ширина окна 920 - неточности сохраняются, как в десктоп версии:


![Image](https://github.com/ya-pomogau/frontend/assets/11219356/8669e0d8-eb3d-4261-8730-a13c6082121b)


ширина окна 919 - пропадает карточка с инфо и аватарка:


![Image](https://github.com/ya-pomogau/frontend/assets/11219356/3d0b4c0d-53ca-4926-a0c9-abb85a337e20)


ширина окна 900 - верхнее меню трансформируется в выпадающее, появляется аватарка


![Image](https://github.com/ya-pomogau/frontend/assets/11219356/1beea948-0196-4c92-b18f-d541eb5bc1bd)

(проверить смену макета на границах ширин 919-920px и 900-901px)
