### ISSUE TITLE
Проверка работы хука "usePermission"

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#195]
1. В хук нужно обязательно добавить проверку на `isRoot`. Если пользователь имеет это свойство со значением `true`, то он может ВСЁ.
2. Длина массива `requirments` должна быть равна длине `hasPermission`. Если да, то `isAllowed` = true иначе `isAllowed` = false

**Comment by INextYP** [comment]
@AlexeyKrutyakov Привет! Ветка для работы `fix/use-permission` команда для перехода в ветку `git checkout fix/use-permission`

**Comment by AlexeyKrutyakov** [comment]
@INextYP 
сделал проверку на isRoot внутри проверки на наличие роли, потому что в типе User поле role обязательное.

1. я бы еще везде поправил requirments на requirements (нужно?) Затронет только файл хука usePermission
2. в коммитах все пишут по-разному, кто-то на русском, кто-то на английском, на каком могу писать? (привык на английском)

**Comment by INextYP** [comment]
> я бы еще везде поправил requirments на requirements

"Везде" - это где? Если править, то сколько модулей это затронет?

**Comment by INextYP** [comment]
> @INextYP 
> сделал проверку на isRoot внутри проверки на наличие роли, потому что в типе User поле role обязательное.
> 
> 1. я бы еще везде поправил requirments на requirements (нужно?) Затронет только файл хука usePermission
> 2. в коммитах все пишут по-разному, кто-то на русском, кто-то на английском, на каком могу писать? (привык на английском)

1. Можно
2. Лучше на английском. Во всех компаниях используется именно такое соглашение

**Comment by AlexeyKrutyakov** [comment]
@INextYP
не совсем понял правильно ли я в карточках указал пулл-реквест, но вроде так.
если что - поправь меня

**Comment by INextYP** [comment]
> @INextYP
> не совсем понял правильно ли я в карточках указал пулл-реквест, но вроде так.
> если что - поправь меня

Да, всё так) Я завтра гляну.
Старайся в PR в описании писать, что было сделано, особенно, если PR громоздский)

**Comment by AlexeyKrutyakov** [comment]
> > [@INextYP](https://github.com/INextYP)
> > не совсем понял правильно ли я в карточках указал пулл-реквест, но вроде так.
> > если что - поправь меня
> 
> Да, всё так) Я завтра гляну. Старайся в PR в описании писать, что было сделано, особенно, если PR громоздский)

подскажи пожалуйста что за PR такой, я пока не в теме

**Comment by INextYP** [comment]
> > > [@INextYP](https://github.com/INextYP)
> > > не совсем понял правильно ли я в карточках указал пулл-реквест, но вроде так.
> > > если что - поправь меня
> > 
> > Да, всё так) Я завтра гляну. Старайся в PR в описании писать, что было сделано, особенно, если PR громоздский)
> 
> подскажи пожалуйста что за PR такой, я пока не в теме 

PR - pull request :)

**Comment by AlexeyKrutyakov** [comment]
понял, поправил описание к PR

**Comment by INextYP** [comment]
@AlexeyKrutyakov Привет, оставил комментарии в коде. Как будет готово - маякуй)

**Comment by AlexeyKrutyakov** [comment]
@INextYP привет, поправил
