### ISSUE TITLE
Исправление верстки и логики работы чата (администратор)

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#196]
В дизайне в разделе "чат" у админа 3 подраздела:
- "Ждут ответа"
- "В работе"
- "Конфликтное закрытие"

а у нас:
- "Конфликты"
- "Конфликты в работе"

В рамках задачи требуется:

1. Переименовать разделы по дизайну. Важно: текущий раздел "конфликты" нужно переименовать в "Конфликтное закрытие";
2. Привести отображение в подразделах к дизайну:
 как пример: в разделе "ждут ответа" в левой части находятся сообщения, на которые не ответил администратор. Справа, если ничего не выбрано, то пустота, если выбрано сообщение то отображается окно с чатом и кнопка "Взять в работу" [ссылка](https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=1537-18236&t=CQXWBWSbQhok84Q3-4)
3. Исправить остальные проблемы, указанные в [комментария проверки](https://github.com/orgs/ya-pomogau/projects/1/views/1?pane=issue&itemId=65408970)

✅ [БРИФ](https://narrow-mountain-bc1.notion.site/3-15-1880e7396a9c4bbda3d1f33103fd01af)

**Comment by INextYP** [comment]
@ArtPsycho Привет! Ветка для работы с задачей `fix/admin-chat` , команда для перехода в ветку `git checkout fix/admin-chat`

⚠ Убедительная просьба, сверяйся с брифом, там очень подробно описано, кто с какими правами может брать чаты в работу и т.д. :)

**Comment by ArtPsycho** [comment]
Привет! Принято)
