### ISSUE TITLE
Исправление раздела "Контакты"

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#197]
На текущий момент данные в разделе полностью статичны.

В рамках задачи нужно:
- подключить бекенд часть для загрузки данных для этой страницы. ⚠ Важно: данные с сервера должны приходить одинаково, как для неавторизованных пользователей, так и для авторизованных
- добавить возможность редактирования данных (ручка для бекенда есть) на странице пользователям, являющихся главным админом (роль админ и isRoot: true).
- исправить ошибки верстки после проверки ⬇ 

[Результаты проверки](https://github.com/orgs/ya-pomogau/projects/1/views/1?pane=issue&itemId=65585059)

**Comment by INextYP** [comment]
@IvannaBalanyuk Привет! Ветка для работы с кодом `fix/contacts`, команда для перехода в ветку `git checkout fix/contacts`. Обязательно сверь итоговый функционал с брифом. Удачи! :)

**Comment by IvannaBalanyuk** [comment]
Ссылка на Pull Request: https://github.com/ya-pomogau/frontend/pull/206
