### ISSUE TITLE
Исправление функционала и верстки редактирования данных пользователя

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#198]
1. При редактировании данных профиля в поле "Номер телефона" можно ввести любое значение. Нужно добавить валидацию.
2. Исправить верстку/ привести её к виду дизайна

Остальные проблемы, которые были найдены указаны в карточке [задачи](https://github.com/orgs/ya-pomogau/projects/1/views/1?pane=issue&itemId=65627923)

**Comment by INextYP** [comment]
@LodeNik23 Привет! Команда для перехода в ветку `git checkout fix/edit-profile-data`. Обязательно проверь итоговую работу по брифу. Удачи :)

**Comment by LodeNik23** [comment]
Так как от верстки шапки съезжала верстка body - поправил немного шапку. 
В попапе с инпутами для изменения данных пользователя  для полного соответствия верске нужно разбивать блок инпутов на два отдельных - пока не стал вносить такие изменения.
Валидация телефона выполняется по образцу при входе/регистрации. При необходимости можно исправить на формат 8(ххх)ххх....
В окне информации пользователя в дефолте только иконка-смайл по центруб а в фигме две иконки. При появлении ключа смещается левее в соответствии с версткой.

https://github.com/ya-pomogau/frontend/pull/207

**Comment by LodeNik23** [comment]
Добавлен вывод сообщения об ошибке и красное подчеркивание невалидного инпута. https://github.com/ya-pomogau/frontend/pull/207
