### ISSUE TITLE
Исправление раздела меню (администратор)

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#199]
На текущий момент у админа при клике на кнопку "меню" появляется 2 раздела:
- связь с администратором
- выход

`Связь с администратором` нужно выпилить и в мобильном меню и на декстопе. 

Важно! У ролей Реципиент и Волонтер эта кнопка должна остаться. Обязательно проверь этот кейс перед сдачей на ревью.

Ссылка на дизайн 
- [Декстоп](https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=6750-23614&t=CQXWBWSbQhok84Q3-4)
- на мобилку дизайн для меню админа отсутствует, но в целом нужно убрать `Связь с администратором`

**Comment by INextYP** [comment]
@LatyshevDD Привет! Команда для перехода в ветку `git checkout fix/admin-menu`. Обязательно проверь, что у остальных ролей функционал остался. Удачи :)

**Comment by LatyshevDD** [comment]
Привет!
Ссылка на pull request - https://github.com/ya-pomogau/frontend/pull/204
