### ISSUE TITLE
 Разбить на задачи "работа с заявками"

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#203]
В рамках задачи нужно проверить верстку страницы "Работа с заявками" у админа (2 раздела: 
- создание заявки;
- настроить баллы
).

В комментариях к карточке пишем все баги, найденные во время проверки.

Код в рамках задачи писать не нужно.

![Image](https://github.com/ya-pomogau/frontend/assets/70805943/9e7df3ef-365a-46d1-ae37-09604672246c)

Важно. На этой же странице, при условии, что у пользователя есть доступ к редактированию баллов или пользователь `isRoot` должна отображаться кнопка `Настроить баллы` [Ссылка_на_макет](https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=6873-17149&t=upnuLhNfpAwwGcX5-4)

Кнопка ведет на страницу "Настроить баллы" - https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=6750-23646&t=upnuLhNfpAwwGcX5-4

**Comment by Anton-Laid** [comment]
### Проверка страницы "Создание / Редактирование заявки"

- Карточки в коде изначально не доделаны и видимо у них старая типизация, так как они не как не совпадают по типизации с нынешнем юзером
![Снимок экрана 2024-06-18 в 20 43 56](https://github.com/ya-pomogau/frontend/assets/113182938/79acbcbb-6f5c-4a59-a193-6493b442401a)
![Снимок экрана 2024-06-18 в 20 42 49](https://github.com/ya-pomogau/frontend/assets/113182938/f3ea0f68-1943-484c-83b7-46396b93f51a)
- Нет вкладки "Реципиент" и "Волонтер"
![Снимок экрана 2024-06-18 в 21 03 53](https://github.com/ya-pomogau/frontend/assets/113182938/0b5181d3-6e1c-4fbb-a191-6d35c8d3bd0c)
- У Input и настройка баллов нет стилей схожих с макетом
![Снимок экрана 2024-06-18 в 20 28 54](https://github.com/ya-pomogau/frontend/assets/113182938/3884d8be-2888-4204-8aeb-9d5af58f747c)
- Input работает
- У карточек тоже нет правильных стилей
![Снимок экрана 2024-06-18 в 20 41 51](https://github.com/ya-pomogau/frontend/assets/113182938/9bfdae53-dff1-4f0d-96e0-d4da1888e9a5)
- Контейнер для карточек тоже нужно поправлять на всех разрешениях
![Снимок экрана 2024-06-18 в 20 42 10](https://github.com/ya-pomogau/frontend/assets/113182938/05598c1e-0d04-4f7e-95ee-df82f76c3a10)
![Снимок экрана 2024-06-18 в 20 42 00](https://github.com/ya-pomogau/frontend/assets/113182938/44e1d2ba-9a3d-40db-839a-169a3b0fc673)
### Страница с баллами
- Кнопка сохранить должна быть по середине
![Снимок экрана 2024-06-18 в 20 55 14](https://github.com/ya-pomogau/frontend/assets/113182938/dd289a5a-a9c8-4459-a305-933dc53dcc1e)
- На кнопке сохранить нет никакого функционала
- На мобильной версии кнопка тоже не по середине и в планшетной версии страница выглядит следующим образом
![Снимок экрана 2024-06-18 в 20 58 37](https://github.com/ya-pomogau/frontend/assets/113182938/c18589a3-8a87-48a1-862d-7d3c898dbe7a)
![Снимок экрана 2024-06-18 в 20 59 59](https://github.com/ya-pomogau/frontend/assets/113182938/ce0f03d9-6632-4c5d-a6c7-682d91cf82d6)
