### ISSUE TITLE
(Второстепенная задача) Исправление верстки чата волонтер + реципиент (Desktop)

### ISSUE THREAD

**Issue by pudgekaramelkin** [ya-pomogau/frontend#208]
В рамках задачи нужно исправить отображение чата с прикрепленным файлом. Сейчас верстка выглядит так:

![Image](https://github.com/ya-pomogau/frontend/assets/70805943/0014721e-d380-43c8-9eea-0dc1990ffac7)

А по дизайну:

![Image](https://github.com/ya-pomogau/frontend/assets/70805943/fcdd5997-5d56-489b-991a-1e82d595f621)

**Comment by INextYP** [comment]
@LatyshevDD `fix/chat-pin-file` ветка
