### ISSUE TITLE
Реализовать возможность открытия чата (реципиент + волонтер)

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#209]
На текущий момент чат не открывается:
- ни в меню по кнопке "Связь с администратором";
![Image](https://github.com/ya-pomogau/frontend/assets/70805943/75b17005-0694-4e7b-99be-1384c0bcfe51)

- ни при клике по кнопке "Чат" в карточке задачи;

![Image](https://github.com/ya-pomogau/frontend/assets/70805943/93a6acce-cc9d-4e37-82a1-1263c0bad5d2)

В рамках задачи требуется реализовать возможность открытия чата в меню и в карточке задачи.

Важно! В карточке к задаче чат можно открыть при соблюдении условий:
- у карточки назначен волонтер (если волонтер === null, то кнопка чата неактивна)
- карточка в активном статусе (не закрыта)

⚠  В дополнение: проверить работу бейджа непрочитанных сообщений:
в таске:
![Image](https://github.com/ya-pomogau/frontend/assets/70805943/2c70bd16-417c-404f-96dd-acd3a54f556d)

в меню:
![Image](https://github.com/ya-pomogau/frontend/assets/70805943/7aae396b-901e-4e9c-8590-c181e571d8a9)

**Comment by INextYP** [comment]
Ветка для работы: `fix/open-chat-modal`

**Comment by LatyshevDD** [comment]
@INextYP А есть логин и пароль для волонтера и реципиента? А то менять state в redux не очень удобно

**Comment by INextYP** [comment]
> @INextYP А есть логин и пароль для волонтера и реципиента? А то менять state в redux не очень удобно

Если ты используешь локальную БД, то можно через компас быстро менять данные. Если используешь реальный бекенд, то пиши мне или Жене в пачке, мы исправим.

Волонтер и реципиент не имеют системы входа через логин-пароль, только вк. Раньше у нас была страница "/pick", возможно она и сейчас работает, если подшаманить.

Кстати, а зачем тебе в этой задаче переключаться между ролями?

**Comment by LatyshevDD** [comment]
@INextYP Просто не совсем разобрался как вывести страницу со списком задач. Базу локальную запустил с данными, но они не подтягиваются в компоненты ProfileCompletedPage и ProfileActivePage. Подумал что не хватает авторизации

**Comment by LatyshevDD** [comment]
@INextYP Вроде разобрался. Добавил массив tasks вручную в props

**Comment by INextYP** [comment]
Вмержено в рамках другого PR. В этот попало слишком много ненужного
