### ISSUE TITLE
Админка. Добавление возможности просмотра пользователей списком

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#211]
В рамках задачи нужно добавить возможность переключения представления карточек пользователей на просмотр списком.
Сейчас реализован такой вариант: [ссылка](https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=6789-20693&t=YtHkJwWd78cN7HCD-4)

то, что сейчас не реализовано: [ссылка](https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=13497-13839&t=YtHkJwWd78cN7HCD-4)

нужно реализовать чтобы нажимая на кнопку.

![Image](https://github.com/ya-pomogau/frontend/assets/70805943/a68dc061-e29b-4994-96da-72073666bf76)

или 

![Image](https://github.com/ya-pomogau/frontend/assets/70805943/a32b4b30-ff61-45bb-b4ab-a886f301908f)

карточки отображались в соответствующем представлении.

⚠ Вторая задача - реализовать возможность скролла (сейчас, со слов заказчика, на этой странице, при большом количестве карточек нет скролла)

**Comment by INextYP** [comment]
Ветка для работы `feat/list-card-format`

**Comment by INextYP** [comment]
+ есть ещё такая багулина

![Image](https://github.com/ya-pomogau/frontend/assets/70805943/dcaaa478-176a-4e02-8737-34f85a7ea65a)

**Comment by daniildd-kh** [comment]
PR: #222

**Comment by daniildd-kh** [comment]
Внес исправления в PR
