### ISSUE TITLE
Добавление функционала редактирования баллов за категории

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#212]
В рамках задачи нужно сделать следующее:
1. Добавить в `BalanceSettings` получение категорий через `useGetCategoriesQuery`
2. Сверить и подкорректировать верстку [ссылка на макет](https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/ЯПомогаю-(Web)?node-id=6750-23646&t=YtHkJwWd78cN7HCD-0)
3. Добавить обновление данных через сервер

**Comment by INextYP** [comment]
Ветка для работы `feat/change-get-and-update-points`

**Comment by IvannaBalanyuk** [comment]
Ссылка на PR: https://github.com/ya-pomogau/frontend/pull/220
