### ISSUE TITLE
Исправить хук usePermission и написать тесты

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#214]

**Comment by INextYP** [comment]
`fix/use-pemission_tests`

**Comment by AlexeyKrutyakov** [comment]
> `fix/use-pemission_tests`

@INextYP Саш, я поправил название ветки (надеюсь это не критичное действие с моей стороны) - ты пропустил букву r
fix/use-peRmission_tests

**Comment by INextYP** [comment]
> > `fix/use-pemission_tests`
> 
> @INextYP Саш, я поправил название ветки (надеюсь это не критичное действие с моей стороны) - ты пропустил букву r
> fix/use-peRmission_tests

Да, отлично, что заметил и исправил :)
