### ISSUE TITLE
Добавить подчеркивание у активной ссылки меню

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#216]
На текущий момент выглядит так:

![Image](https://github.com/ya-pomogau/frontend/assets/70805943/89729b46-7400-42ce-926d-27fa1087d862)

Хотя мы находимся в личном кабинете.

После исправления проверить у остальных ролей, что ничего не сломалось

**Comment by INextYP** [comment]
`fix/active-nav-menu-styles`

**Comment by LodeNik23** [comment]
https://github.com/ya-pomogau/frontend/pull/223
