### ISSUE TITLE
(Второстепенная задача) Исправление верстки чата волонтер + реципиент (Mobile)

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#225]
В рамках задачи нужно исправить верстку чата для волонтера и реципиента для мобильного разрешения.
Основные проблемы:
1. Кнопки карточки задачи перекрывают чат
![Image](https://github.com/ya-pomogau/frontend/assets/70805943/ff4e916b-a95d-4169-8514-e530d7759f16)

2. Не совпадает верстка окна чата (в дизайне отсутствует рамка у мобильной версии)
3. Не совпадает верстка с прикрепленным файлом

**Comment by INextYP** [comment]
fix/chat-mobile

**Comment by daniildd-kh** [comment]
PR: #235

**Comment by daniildd-kh** [comment]
Случайно закрыл тикет
