### ISSUE TITLE
Исправления в разделе политики конфиденциальности

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#226]
1. Добавить скролл-бар.
3. Редактирование политики конфиденциальности главным админом.
4. Исправление в моб. версии (на текущий момент она не совпадает с дизайном)

**Comment by INextYP** [comment]
fix/privacy_policy

**Comment by LatyshevDD** [comment]
@INextYP При запуске проекта в ветке fix/privacy_policy вылезает целая простыня ошибок. Хочу уточнений их надо править перед тем как приступить к работе? Или лучше новую ветку создать?



![Image](https://github.com/ya-pomogau/frontend/assets/110352990/b7fbf64e-d52e-44c8-8be0-87f05dc708f5)
![Image](https://github.com/ya-pomogau/frontend/assets/110352990/898559f1-49e4-4f8f-8ec5-8276cceed413)
![Image](https://github.com/ya-pomogau/frontend/assets/110352990/4ab00b49-d274-4c23-9f66-2f4e1b0110bb)
![Image](https://github.com/ya-pomogau/frontend/assets/110352990/0456c032-1993-40cb-910a-1746e1018f84)
![Image](https://github.com/ya-pomogau/frontend/assets/110352990/f555a831-65a6-4711-97fb-13496bab7380)
![Image](https://github.com/ya-pomogau/frontend/assets/110352990/02726499-0365-46c9-a21b-eaaabb5a4bb6)

**Comment by INextYP** [comment]
А ты зависимости поставил?

**Comment by LatyshevDD** [comment]
@INextYP Помогло. Спасибо! Еще хотел уточнить, как требуется реализовать редактирование текстового поля политики. Предполагается что новый текст будет вводиться с использованием разметки markdown? Иначе не совсем понятно, как должны быть реализованы отступы и списки.и

**Comment by kspshnik** [comment]
> Предполагается что новый текст будет вводиться с использованием разметки markdown? Иначе не совсем понятно, как должны быть реализованы отступы и списки.и

Да, там компонент показа сделан из расчёта, что ему придёт MD.

**Comment by LatyshevDD** [comment]
@kspshnik @INextYP Все сделано - https://github.com/ya-pomogau/frontend/pull/229
