### ISSUE TITLE
Страница "Работа с заявками"

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#231]
В рамках задачи необходимо реализовать страницу "Создание/ редактирование заявки" в админке.

Страница состоит из подразделов:
1. Список всех пользователей (в зависимости от выбранного таба будут показываться все АКТИВНЫЕ пользователи)
2. При нажатии на пользователя из раздела выше происходит переход на подстраницу где в зависимости от роли поменяется контент:
       a.  `Реципиент` -  должна появиться кнопка "Создать заявку", а также загрузиться список АКТИВНЫХ заявок выбранного реципиента. Можно создать заявку под текущим выбранным пользователем
      б. `Волонтер` - открывается список АКТИВНЫХ заявок пользователя
3. При нажатии на "Поиск" в подразделе - происходит переход на страницу "Работа с заявками"

⚠ Важно! Проверьте бриф. Не все пользователи-админы могут создавать заявки или выполнять какие-то действия.

Прямая ссылка на макет:

1. https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=6740-40599&t=Hw7m5IM81oQSyDg3-4
2. https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=6740-47649&t=Hw7m5IM81oQSyDg3-4
3. https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=6740-48063&t=Hw7m5IM81oQSyDg3-4

**Comment by INextYP** [comment]
feat/admin-task

**Comment by INextYP** [comment]
@Elena-Orekhova в дополнение -  реализация адаптива будет в рамках другой задачи. Пока что формируем основное разрешение

**Comment by Elena-Orekhova** [comment]
https://github.com/ya-pomogau/frontend/pull/238
