### ISSUE TITLE
Функциональность создания админа

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#232]
В рамках задачи необходимо реализовать возможность создания администратора.
⚠ Важно! Возможность создания админа, как раздел "администраторы" должны быть только у `root` админа.
⚠ Важно №2 реализация адаптива будет в рамках другой задачи. Пока что формируем основное разрешение 

1. Раздел исправляем с "Админы" на "Администраторы"
2. Проверяем, что карточки админов отображаются по дизайну + загружаются с сервера с соответствующей ручки
3. При нажатии на "Создать администратора" открывается раздел с формой для создания + меняется шапка на "Добавление администраторов" `фильтр тут не нужен, это ошибка дизайна`
4. Форму создания админа желательно сделать с использованием библиотеки `react-hook-form` (зависимости уже установлены)
Ссылка на визуальное представление - [тык](https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=459-5163&t=Hw7m5IM81oQSyDg3-4)
5. После нажатия кнопки "Добавить" отправляется запрос на сервер, создаётся новый админ (предварительно запоминаем данные для входа, так как рассылки нет) и осуществляется переход в раздел "Подтверждение/ Блокировка"
6. Не в приоритете:
   - смена паролей админам
   - добавление новых привилегий

Ссылка на форму создания админа - [тык](https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=6762-13537&t=Hw7m5IM81oQSyDg3-4)

**Comment by INextYP** [comment]
feat/create-admin

**Comment by daniildd-kh** [comment]
PR: #240 
Прошу прощения, что задержал задачу по срокам
