### ISSUE TITLE
Доработать фильтр для карты заявок и активных заявок

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#234]
Проверить работу фильтра на карте заявок.

⚠  Важно. В дизайне фильтр отображается у неавторизованного пользователя, такого быть не должно. 

- [x] Фильтр отображается только у пользователя с ролью `Волонтер`, который подтвержден администратором. В ином случае не показываем фильтр
- [x] У неавторизованных пользователей на карте фильтр не отображается
- [x] Проверена работа со всеми кейсами фильтрации
Ссылка на компонент фильтра в макете https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=503-6500&t=Hw7m5IM81oQSyDg3-4

**Comment by INextYP** [comment]
feat/active-tasks-filter

**Comment by makimaki04** [comment]
@INextYP 
В Categories-block не совсем понятно для чего нужна данная проверка волонтера, которая блокирует выбор категорий фильтра(хук usePermission отрабатывает неправильно). Также из-за неправильно поставленного условия блокируются категории фильтра у реципиента. В тз и макете не увидел условий блокировки категорий. Нужна ли вообще данная проверка?
![Image](https://github.com/ya-pomogau/frontend/assets/143491619/0c6c5319-b75d-4d56-98b5-87b6aaf69616)
Условие блокировки:
![Image](https://github.com/ya-pomogau/frontend/assets/143491619/1f5e261d-bb46-4d21-95b7-2005ecd2afba)

![Image](https://github.com/ya-pomogau/frontend/assets/143491619/ecbc3448-5c65-4331-b1ec-f8f72c73b5df)

**Comment by INextYP** [comment]
@makimaki04 Привет! В брифе всё указано :) 
![image](https://github.com/ya-pomogau/frontend/assets/70805943/2754e91d-a064-4c06-b5e0-45040d9dca91)

Раздел `Волонтер - Статусы волонтера`

**Comment by makimaki04** [comment]
Увидел, спасибо. А то я искал отдельное упоминание фильтра. Буду внимательнее

**Comment by makimaki04** [comment]
Привет! Ссылка на PR:
[Доработать фильтр для карты заявок и активных заявок #234](https://github.com/ya-pomogau/frontend/pull/236)
