### ISSUE TITLE
Доработки по фильтру

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#239]
🤕  В рамках задачи требуется исправить отображение компонента фильтра 
- [x] Категории должны тянуться с бекенда в файле `CategoriesBlock`
- [x] При наведении на чекбокс курсор должен быть типа `pointer` (исключение - выключенные категории)
- [x] Настроить размеры фильтра по дизайну
- [x] Исправить неккоректный сброс по кнопке "Сбросить фильтры"
- [x] Исправить фокус эффект в timePicker 
![Image](https://github.com/ya-pomogau/frontend/assets/70805943/a9124f40-8a94-448f-8e8d-dd58ccce823e)
- [x] Исправить привязку открытого фильтра (если на декстопе пролистрать страницу вниз и открыть фильтр, то получим):
![Image](https://github.com/ya-pomogau/frontend/assets/70805943/65a6f0b5-3583-40e0-90a5-78e922ab479e)
- [x] Добавить рамку у календаря
- [x] Убрать ненужный текстовый блок под календарем
![Image](https://github.com/ya-pomogau/frontend/assets/70805943/4a11f090-af49-4f95-8427-2f8d54375949)
- [x] Почистить компоненты, относящиеся к календарю от консолей, неиспользуемых импортов
- [x] Исправить мобильный формат (есть проблема с календарем)

**Comment by INextYP** [comment]
`bugfix/filter`

**Comment by makimaki04** [comment]
@INextYP 
Саш, привет, вопрос по поводу фокуса на инпуте выбора времени. Подскажи, пожалуйста, а есть ли вообще возможность настраивать цвет выделения текста у инпута типа тайм. Я уже очень долго пытаюсь найти решение данной проблемы и ничего не выходит.

**Comment by INextYP** [comment]
> @INextYP 
> Саш, привет, вопрос по поводу фокуса на инпуте выбора времени. Подскажи, пожалуйста, а есть ли вообще возможность настраивать цвет выделения текста у инпута типа тайм. Я уже очень долго пытаюсь найти решение данной проблемы и ничего не выходит. 

А зачем тебе цвет выделения? В большей степени по пункту, связанному с фокусом нужно убрать рамку и всё) Выделение текста можно настраивать, но нам это не требуется

**Comment by makimaki04** [comment]
> > @INextYP 
> > Саш, привет, вопрос по поводу фокуса на инпуте выбора времени. Подскажи, пожалуйста, а есть ли вообще возможность настраивать цвет выделения текста у инпута типа тайм. Я уже очень долго пытаюсь найти решение данной проблемы и ничего не выходит. 
> 
> А зачем тебе цвет выделения? В большей степени по пункту, связанному с фокусом нужно убрать рамку и всё) Выделение текста можно настраивать, но нам это не требуется

Тогда лучше сразу уточню какая именно проблема календаре мобильного формата, чтобы снова не сделать лишней работы. Подскажи, пожалуйста:)

**Comment by INextYP** [comment]
> > > @INextYP 
> > > Саш, привет, вопрос по поводу фокуса на инпуте выбора времени. Подскажи, пожалуйста, а есть ли вообще возможность настраивать цвет выделения текста у инпута типа тайм. Я уже очень долго пытаюсь найти решение данной проблемы и ничего не выходит. 
> > 
> > А зачем тебе цвет выделения? В большей степени по пункту, связанному с фокусом нужно убрать рамку и всё) Выделение текста можно настраивать, но нам это не требуется
> 
> Тогда лучше сразу уточню какая именно проблема календаре мобильного формата, чтобы снова не сделать лишней работы. Подскажи, пожалуйста:)

Он очень криво отображался, не так, как в дизайне

**Comment by makimaki04** [comment]
Привет! Ссылка на PR: https://github.com/ya-pomogau/frontend/pull/242/commits
