### ISSUE TITLE
Исправить кнопку "Личный кабинет" в бургер-меню

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#244]
Нужно, чтобы в бургер меню, при нажатии на "Личный переход", осуществлялся переход к странице [ЛК](https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=7169-23103&t=ufFkK99mRP3RCq0S-4) с соответствующей отрисовкой для определенной роли

**Comment by INextYP** [comment]
`fix/burger-menu`

**Comment by LatyshevDD** [comment]
@INextYP Приветствую! Правильно ли я понял, что страницы "Личный кабинет" предусмотрены только для ролей "Администратор", "Реципиент" и только на мобильных разрешениях? Мне не удалось обнаружить готовых версток этих страниц. Так и есть и нужно их сделать или я не там искал?

**Comment by INextYP** [comment]
> @INextYP Приветствую! Правильно ли я понял, что страницы "Личный кабинет" предусмотрены только для ролей "Администратор", "Реципиент" и только на мобильных разрешениях? Мне не удалось обнаружить готовых версток этих страниц. Так и есть и нужно их сделать или я не там искал?

Привет. Личный кабинет есть у каждой роли. Это некая группа главных роутов.
У реципиента это активные заявки;
У волонтёра это карта заявок;
У админа это вроде подтверждение пользователей.

Сейчас кнопка не работает вообще на мобилке, а нужно, чтобы перебрасывала на main роут в зависимости от роли

**Comment by LatyshevDD** [comment]
@INextYP у админа кнопка работает и перебрасывает ра страницу "подтверждения пользователей"


![Image](https://github.com/user-attachments/assets/85a9e7a3-4516-457c-86af-d59ecfacc064)

**Comment by LatyshevDD** [comment]
@INextYP Подскажи пожалуйста как осуществить вход под учетками реципиента и волонтера?

**Comment by INextYP** [comment]
> @INextYP Подскажи пожалуйста как осуществить вход под учетками реципиента и волонтера?

Просто зарегайся через вк реципиентом. Если ты используешь свой бекенд локально, то можешь через Компасс удалить пользователя и снова зарегаться как волонтер

**Comment by LatyshevDD** [comment]
@INextYP Спасибо! Все сработало. Но кнопка "Личный кабинет" на первый взгляд работает исправно. В ЛК реципиента осуществляется переход к активным заявкам, в ЛК волонтера к карте заявок. Прошу уточнить задачу.


![Image](https://github.com/user-attachments/assets/1473c3e5-205b-4426-8a79-2c4095d9c9ea)
![Image](https://github.com/user-attachments/assets/ea27a50d-a627-43c2-9019-89476eda49ce)

**Comment by INextYP** [comment]
Хм, видимо кто-то незаметно всё исправил.

Давай тогда так. Исправь отображение меню. Оно куда-то уехало не туда. Могу новую задачу создать или же просто исправить заголовок и описание к этой задаче!?

**Comment by LatyshevDD** [comment]
@INextYP Ок. Предлагаю просто заголовок у этой задачи изменить

**Comment by LatyshevDD** [comment]
@INextYP поправил - https://github.com/ya-pomogau/frontend/pull/251
