### ISSUE TITLE
Админка. Создание / Редактирование заявки. Исправление вёрстки и логики работы

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#246]
В рамках задачи требуется:
1. Исправить отображение карточек. Сейчас они не похожи на макет.
2. Реализовать загрузку и отображения пользователей через сервер, а не на моках

**Comment by INextYP** [comment]
`fix/create-card-admin`

**Comment by makimaki04** [comment]
@INextYP Саш, привет, подскажи, пожалуйста, нужны ли кнопки звонка и чата в карточке юзера?
![Image](https://github.com/user-attachments/assets/903d27c6-5b65-4d7d-9204-c757ee104a34)

Судя по макету данные кнопки не нужны 
https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/ЯПомогаю-(Web)?node-id=459-6425&t=8LMVFwlXnWKrni1w-0

но в брифе есть такая фраза: - Администратор работа в разделе “Заявки/ Работа с заявками”  вкладка “Волонтер/Реципиент”
     Кнопки для связи с реципиентом (“📞”, “🗨”) не активны

**Comment by makimaki04** [comment]
Привет! Ссылка на PR: https://github.com/ya-pomogau/frontend/pull/257
