### ISSUE TITLE
Реализация системной мидвары для подключения к Socket.io

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#254]
В рамках задачи требуется:
Реализовать мидвару для обработки системных сообщений. 

- [x] Реализовать мидвару нужно в папке `Services`
- [x] Мидвара должна использовать библиотеку `Socket.io`, а не встроенное Websockets API (класс `WebSocket`)
- [x] url для подключения должен браться из `.env`-файла.

На начальном этапе необходимо обработать следующие события WS:
- [x] Init
- [ ] Close
- [ ] Message

Аналогичное redux middleware реализовывалось в проектной работе Stellar Burger курса Web+, но на встроенном Websockets API.

[Документация библиотеки Socket.io](https://socket.io/docs/v4/)

**Comment by INextYP** [comment]
`feat/socket-middleware`

**Comment by gvozdenkov** [comment]
@kspshnik @INextYP Взял, но мне нужно вспомнить про сокеты, nest и Redux... Если будет затык - приду за помощью %)

**Comment by kspshnik** [comment]
> [@kspshnik](https://github.com/kspshnik) [@INextYP](https://github.com/INextYP) Взял, но мне нужно вспомнить про сокеты, nest и Redux... Если будет затык - приду за помощью %)

Nest.js тут не при базаре, это _фронтовая_ задачка ;) 
Но тронул - ходи © ;)

Пиши вопросы, как появятся.

**Comment by gvozdenkov** [comment]
@kspshnik Я понимаю что фронтовая, но мне чтобы в сокеты и чат погрузиться всё равно это нужно пощупать

**Comment by gvozdenkov** [comment]
@INextYP @kspshnik Я сделяль! Но с сокетами и редаксом ещё вспоминаю / изучаю. После логина идёт подключение к сокету.

![Image](https://github.com/user-attachments/assets/6efdd352-78dd-4b89-b899-8fd1b28f7118)

- В отдельном коммите добавил `.env.example` и подправил `vite.config.ts`, чтобы подгружались переменные из `.env.development` в режиме разработки. Т.е. новый конфиг ничего не меняет, просто делает порт, на котором запускается vite в dev режиме не захардкоженным в скрипте.
- Скрипт в `package.json` тоже подправил, чтобы порт vite не переназначался, а брался из `.env.development`
- В отдельном коммите добавил докер файлы

##  БЕЗ докера:

### Фронт + удалённый сервер

1. Скопировать `.env.dev.remote.example` в `.env.development`
2. Запустить `npm run dev`. Фронт по адресу http://localhost:3000

### Фронт + локальный сервер

1. Скопировать `.env.dev.example` в `.env.development`
2. Исправить SERVER_URL на тот, где локальный сервер
3. Запустить `npm run dev`. Фронт по адресу http://localhost:3000

##  С докером:

### Фронт + удалённый сервер

1. Скопировать `.env.dev.remote.example` в `.env.dev`
2. Запустить фронт в докере:

```shell
`docker compose -f docker-compose.dev.yml --env-file=.env.dev up --build`

# или с помощью Makefile
make run-dev
```

### Фронт + локальный сервер

1. Скопировать `.env.dev.example` в `.env.dev`
2. Исправить SERVER_URL на тот, где локальный сервер
3. Запустить фронт в докере:
4. 
```shell
`docker compose -f docker-compose.dev.yml --env-file=.env.dev up --build`

# или с помощью Makefile
make run-dev
```

**Comment by INextYP** [comment]
@gvozdenkov а где PR?)

**Comment by gvozdenkov** [comment]
@INextYP PR https://github.com/ya-pomogau/frontend/pull/269

**Comment by gvozdenkov** [comment]
@kspshnik @INextYP @IvannaBalanyuk Ребят, я чёт туплю пока по сокетам страшно. Мне нужно это покурить, но это уже становится долго. @IvannaBalanyuk Можешь взять это, раз ты уже с сокетами больше дружишь?

**Comment by INextYP** [comment]
Дополнение. Нужно исправить косяки в `PR`
