### ISSUE TITLE
Исправления в работе с неподтвержденным реципиентом

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#258]
В рамках задачи необходимо:
- [x] Зарегаться как реципиент (выбрать "Нужна помощь" при регистрации)

Что нужно исправить/ добавить:
- [x] После регистрации реципиенту нужно показывать надпись "Спасибо за регистрацию. Как только амнинистратор подтвердит Вашу учетную запись, Вы сможете создавать заявки."
- [x] После регистрации реципиента встречает страница "Активные заявки", где отображается "У Вас пока нет заявок" а также кнопка "Хотите создать заявку?" при нажатии на которую показывается модалка с текстом "Вы пока не можете создавать заявку. Дождитесь подтверждения администратора".

**Внешний вид по этим кейсам описан в дизайне:**
- Декстопная версия [тык](https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=6906-27554&t=IuWSIWeqmjo6G8gj-4)
- Мобильная версия [тык](https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=7169-22668&t=IuWSIWeqmjo6G8gj-4)

**Исправление в логике работы RTK Query на страницах "Активные заявки" и "Завершенные заявки"**
- [x] Исключить запросы на бекенд за активными и завершенными заявками в случае, если Реципиент НЕ подтвержден админом

**Comment by INextYP** [comment]
Ветка для работы `fix/unconfirmed-recipient`

**Comment by KuzmichevaES** [comment]
Привет! По выводу надписи и модалки у неподтвержденного реципиента вроде бы нашла в чем проблема. 
После первой регистрации данные о User возвращаются без поля status (оно не обязательное, но на нем завязана логика работы вывода надписи и модалки).


![Image](https://github.com/user-attachments/assets/d7250227-7a6a-4982-9bad-df5a3a747404)

 Если при пустом поле поставить status unconfirmed по умолчанию, то всё работает. Но не уверена, что это ничего не сломает. Насколько корректно будет так решить задачу? Или лучше с бэка всегда возвращать поле status?

**Comment by kspshnik** [comment]
> Если при пустом поле поставить status unconfirmed по умолчанию, то всё работает. Но не уверена, что это ничего не сломает. Насколько корректно будет так решить задачу? Или лучше с бэка всегда возвращать поле status?

Спасибо! Конечно, с бэка.

https://github.com/ya-pomogau/backend/issues/130

**Comment by KuzmichevaES** [comment]
Привет! Отправлен PR https://github.com/ya-pomogau/frontend/pull/265. 
Запросы на сервер исключены за завершенными заявками, если реципиент не подтвержден. 
Остальное должно работать корректно, если с бэка будет приходить status после первичной регистрации.

**Comment by kspshnik** [comment]
>  Остальное должно работать корректно, если с бэка будет приходить status после первичной регистрации.

Сегодня вечером сделаю [#130 на бэкенде](https://github.com/ya-pomogau/backend/issues/130)
