### ISSUE TITLE
Исправление в контейнере страницы

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#259]
В рамках задачи необходимо сделать единый контейнер для контента, который будет синхронно сживаться при изменении размера страницы. Контент из него выпрыгивать не должен.

Под контейнером подразумевается область, отмечeнная красным:

![Image](https://github.com/user-attachments/assets/4b2cae89-5a97-46f4-9c4f-92e64c69099d)

Текущая поломанная ситуация (одна из), которой быть не должно:

![Image](https://github.com/user-attachments/assets/bd6f39f3-8aa3-4a38-a6b3-97a7866ef9ed)

После исправления ОБЯЗАТЕЛЬНО проверить все страницы (под ролью, которой работается + в админки) на предмет того, что ничего не сломалось ОТ декстопного разрешения и ДО мобильного

**Comment by INextYP** [comment]
Ветка для работы `fix/page-container`

**Comment by Elena-Orekhova** [comment]
https://github.com/ya-pomogau/frontend/pull/266
