### ISSUE TITLE
Исправления верстки в карточке задачи

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#271]
Ветка для работы - `fix/task-card`

В рамках задачи необходимо исправить отображение карточки задачи.

Сейчас ситуация следующая:
![Image](https://github.com/user-attachments/assets/ba9cd16c-3631-4647-982a-87ab9456661c)

![Image](https://github.com/user-attachments/assets/a24502e2-75cc-4daa-b427-aa423310a942)

А должно быть как в дизайне:

![Image](https://github.com/user-attachments/assets/c66ac39b-1454-43a3-a52d-ca26dec06a48)

- [x] Исправить отображение длинного текста
- [x] Проверить верстку карточки для декстопного разрешения (близимся к Pixel Perfect)
- [x] Проверить верстку карточки для мобильного разрешения (близимся к Pixel Perfect)
- [x] Добавить скролл-бар на страницу "Активные заявки" и "Завершенные заявки". Сейчас выглядит так:
![Image](https://github.com/user-attachments/assets/a2d44ae6-2a79-4672-b689-abd3e488baed)
- [ ] После работы над задачей код почищен от неиспользуемых импортов, консолей и комментариев

**Comment by Evgeniy-Hozyainov** [comment]
Как мне увидеть список задач, когда я захожу в систему под своим VK аккаунтом?
Сейчас чтобы как-то отобразить задачи я создал моки для компонента **`TaskList`** 

[https://github.com/user-attachments/assets/9eecf1a4-fa63-4b69-b502-a9fccdcfef72](https://github.com/user-attachments/assets/9eecf1a4-fa63-4b69-b502-a9fccdcfef72)

Что имеется ввиду под задачей - Добавить скролл-бар на страницу "Активные заявки" и "Завершенные заявки"?
Что именно должен прокручивать скролл? Только карточки задач между компонентом **`SmartHeader`** и цыетной полоской внизу экрана?
Цветная полоска всегда должна быть видима на экране и фиксировано расположена внизу окна просмотра браузера? (сейчас это не так)
