### ISSUE TITLE
Исправления в странице "Статистика"

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#278]
Ветка для работы - `fix/statistic-page`

В рамках задачи необходимо:
- [x] Проверить и исправить вёрстку разделов "Заявки" и "Пользователи" (близимся к Pixel Perfect)
- [x] Починить верстку календаря при выборе периода. Сейчас ситуация такая:
![Image](https://github.com/user-attachments/assets/620505d1-9c2c-4e10-9a91-2f802e2a1919)
Почитать в доке, как стилизовать календарь - https://reactdatepicker.com/
- [x] Починить селекты выбора "Статуса заявки", "Роли", "Статуса"
- [x] Реализовать работу с формой через библиотеку `react-hook-form` (пункт сложный, если будут вопросы - спрашивайте)
- [x] После окончания работы над задачей код почищен от консолей, неиспользуемых  импортов и т.д.

**Comment by makimaki04** [comment]
@INextYP 
Саш, привет, а что не так с селекторами выбора заявки, статуса и роли?

**Comment by INextYP** [comment]
> @INextYP 
> Саш, привет, а что не так с селекторами выбора заявки, статуса и роли?

Привет. Они сейчас выглядят по дизайну?

**Comment by makimaki04** [comment]
Вот скриншоты с ПП. Изначально такими и были, я только поправил весртку для схожести с макетом

![Image](https://github.com/user-attachments/assets/0c69acef-e0b1-4f95-957c-67ad6e21662a)



![Image](https://github.com/user-attachments/assets/1952afba-a0e4-4081-8f35-7d99fc041245)



> > [@INextYP](https://github.com/INextYP)
> > Саш, привет, а что не так с селекторами выбора заявки, статуса и роли?
> 
> Привет. Они сейчас выглядят по дизайну?

**Comment by INextYP** [comment]
По верстке ок, а по логике явно был косяк, что когда выбрал options из списка, а потом закрыл селект, то непонятно что ты выбрал.
Там в инпуте вроде должно показаться выбранные данные

**Comment by makimaki04** [comment]
Думал об этом. Просто в макете выбранный селект не показывается в инпуте. Сделаю. 
И еще вопрос по библиотеке react-hook-form. Почитал документацию и примеры. Но не особо понятно, как применить это к нашей форме.  Для чего вообще использовать тут эту библиотеку? Если для регистрации данных из полей формы и удобного их использования, то тогда не особо понятно, как получать данные из кастомных компонентов, например DatePicker и тд. Попробовал с помощью Контроллеров описанных в документации, но не получилось. Может быть я не правильно понял суть использования данной библиотеки по отношению к нашей форме?

**Comment by makimaki04** [comment]
> По верстке ок, а по логике явно был косяк, что когда выбрал options из списка, а потом закрыл селект, то непонятно что ты выбрал. Там в инпуте вроде должно показаться выбранные данные

Думал об этом. Просто в макете выбранный селект не показывается в инпуте. Сделаю.
И еще вопрос по библиотеке react-hook-form. Почитал документацию и примеры. Но не особо понятно, как применить это к нашей форме. Для чего вообще использовать тут эту библиотеку? Если для регистрации данных из полей формы и удобного их использования, то тогда не особо понятно, как получать данные из кастомных компонентов, например DatePicker и тд. Попробовал с помощью Контроллеров описанных в документации, но не получилось. Может быть я не правильно понял суть использования данной библиотеки по отношению к нашей форме?

**Comment by INextYP** [comment]
> > По верстке ок, а по логике явно был косяк, что когда выбрал options из списка, а потом закрыл селект, то непонятно что ты выбрал. Там в инпуте вроде должно показаться выбранные данные
> 
> Думал об этом. Просто в макете выбранный селект не показывается в инпуте. Сделаю. И еще вопрос по библиотеке react-hook-form. Почитал документацию и примеры. Но не особо понятно, как применить это к нашей форме. Для чего вообще использовать тут эту библиотеку? Если для регистрации данных из полей формы и удобного их использования, то тогда не особо понятно, как получать данные из кастомных компонентов, например DatePicker и тд. Попробовал с помощью Контроллеров описанных в документации, но не получилось. Может быть я не правильно понял суть использования данной библиотеки по отношению к нашей форме?

Не всегда дизайн позывает все кейсы. Часто нужно додумывать. Становиться на место пользователя и думать - "А удобно ли этим пользоваться".

Касательно библиотеки. Мы сейчас приводим всё к единому формату работы с формами. Не важно сколько инпутов на странице - всё должно работать по единому механизму

**Comment by makimaki04** [comment]
@INextYP
Привет! Ссылка на PL: https://github.com/ya-pomogau/frontend/pull/318

**Comment by makimaki04** [comment]
@INextYP 
Отправил исправления. По поводу env файла. Я его не удалял, а переименовал так, как ты в пачке писал: env.development.example
