### ISSUE TITLE
Исправления в фильтре

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#280]
Ветка для работы - `fix/filter`

В рамках задачи необходимо исправить ошибки в компоненте фильтра `src/features/filter/filter.tsx`:
- [ ] На текущий момент можно поставить чекбокс "По дате" в активное состояние, но снять нельзя. Нужно исправить
- [ ] Необходимо исправить логику работы компонента и настроить его работу с помощью хука `useForm` из библиотеки `react-hook-form`
- [ ] В компоненте нужно полностью избавиться от `defaultObjFilteres`
- [ ] Не давать применить фильтр, если ничего не выбрано (выключаем кнопку)
- [ ] Если после фильтрации ничего не найдено, то выводить текст на страницу "По вашему запросу ничего не найдено"

**Comment by kspshnik** [comment]
Задача исполняется в рамках #386
