### ISSUE TITLE
Реализация кастомного хука для проверки статуса online/offline

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#286]
Работаем в ветке `feat/use-is-online-hook`

В рамках задачи необходимо реализовать хук, который будет проверять, онлайн ли пользователь или нет.
Хук должен возвращать `boolean` - true или false.

Доп задача со звёздочкой - написать для этого хука тесты.

**Comment by kspshnik** [comment]
Ты имеешь в виду - текущий юзверь или произвольный?

**Comment by INextYP** [comment]
> Ты имеешь в виду - текущий юзверь или произвольный?

Текущий. Возможно, что это будет бесполезный функционал, но раз в дизайне есть отображение плашки, что пропал интернет, то сделаем...
