### ISSUE TITLE
Правки в роли Волонтер. Карта

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#287]
Ветка для работы `fix/map`

Работаем в рамках роли "Волонтер" и "Неавторизованный пользователь". Если вы регались под ролью "Реципиента", то напишите тимлиду - исправим.

В рамках задачи необходимо доработать/ исправить.

- [x] При клике по таске карта должна центрироваться
- [x] Карточка на карте - на карточке задачи нужно маскировать номер
- [x] Карточка на карте - исправить отображение при длинном тексте
- [x] Исправление верстки карточки на карте. Близимся к Pixel Perfect
- [x] Если волонтер не подтвержден и кликает на "откликнуться" то не нужно отправлять запрос на `/accept`
- [x] Если волонтер подтвержден, то он может взять заявку в работу (сейчас показывается попап, что чтобы взять в работу заявку нужно дождаться подтверждения...)

- [x] После работы над задачей проверено, что ничего не сломалось.
- [x] Код почищен от консолей, лишних импортов, комментариев

**Comment by TankaShwed** [comment]
> Карточка на карте - на карточке задачи нужно маскировать номер

Для неавторизированных пользователей не делается запрос на сервер для получения списка задач.

> Карточка на карте - исправить отображение при длинном тексте

Уже работает

> Если волонтер не подтвержден и кликает на "откликнуться" то не нужно отправлять запрос на /accept

Уже работало.

> Если волонтер подтвержден, то он может взять заявку в работу (сейчас показывается попап, что чтобы взять в работу заявку нужно дождаться подтверждения...)

IsActive  с бэкенда не приходит.

**Comment by TankaShwed** [comment]
вот мой пул реквест по этой [задаче](https://github.com/ya-pomogau/frontend/pull/321) @INextYP @kspshnik
