### ISSUE TITLE
Проверка сторибука

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#353]
В рамках задачи необходимо только проверить сторибук.
Все исправления будут производиться после сдачи этой задачи.

Результом выполнения этой задачи должен быть стисок такого вида:

кнопка:
- сторис запускается;
- переключалки работают и т.д.

**Comment by ac1deye** [comment]
## UIKit

### Icons:

Работает: color, size, icon, width, height.

---

### FormElements:

- PasswordInput

	Работает: label, placeholder.

- Checkbox

	Работает: label, disabled, checked

	**defaultChecked: boolean - изменение значения ничего не меняет**

- Fieldset

	Работает: title.

	**view - работает в примерах, но не работает при изменении значения в сторибуке**

- InputAddress

	**сторя не запускается**

- InputPhone

	Работает: label, error, errorText

	**ошибка некорректного номера телефона отображается без error true**

- Input

	Работает: label, placeholder, error, customIcon

	**проблемы с версткой customIcon**

- RadioButton

	Работает: label, disabled, checked

- Select

	Работает: label, options

	**Не работает: placeholder, error**

	**не отображается placeholder, выбранный элемент**

- TextArea

	Работает: label, placeholder

---

### Buttons

- DropDownMenuButton
	
    **children: string - плохой выбор нейминга переменной. Меняет текст в кнопке**
	
    **buttonType - не описаны возможные значения. Работает как boolean - есть значение иконка чата и цвет текста синий, нет значения - иконка logout и цвет черный**
	
    **isDisabled - в состоянии с иконкой чата изменяется размер, цвет иконки, кнопка остается кликабельной. В состоянии с иконкой logout ничего не происходит**
	
    **isMobile проблемы с версткой. Справа от кнопки появляется трапеция в значении true**

- ArrowButton
	
    Работает: label, customIcon, disabled

- Button

	Работает: buttonType, label, size, customIcon, disabled
	
    **Нет возможность проверить: actionType**
	
    **isLoading - лидер отображается за пределами кнопки**

- CardButton
	
    Работает: text, customIcon, isActive

- EditButton
	
    Работает: label, disabled

- RoundButton
	
    Работает: customIcon, unreadMessages, disabled
	
    **buttonType - при выборе значения location кнопка становится больше. add еще больше.**
	
    **size - размер не меняется в некоторых случаях в зависимости от buttonType**

- SquareButton
	
    Работает: buttonType, customIcon, disabled
	
    **disabledColor: boolean - переменная просто меняет цвет иконки. Нужно ли?**
	
    **есть незадокументированное свойство taskId. Кажется, что это бизнес логика, за которую компонент не должен отвечать.**

- ExcelButton
	
    **У компонента нет свойств. Компонент невозможно переиспользовать.**

- SettingsButton
	
    **У компонента нет свойств. Компонент невозможно переиспользовать.**

- ViewModeButton

	Работает: modeIcon, selected, disabled

_______

- Tooltip
	
    Работает: visible

	**Не описаны возможные значения pointerPosition. Изменение значения на right ни к чему не приводит**

- ButtonContainer

	Работает: overlayVisible, border, size

- Accordion
	
    Работает: arrayOptions, placeholder
	
    **при выборе аккордеон не сворачивается, placeholder не меняется на текст выбранного элемента**

- Avatar
	
    Работает: avatarLink

- BottomBar
	
    **Не работает**

- CategoriesBackground
	
    Работает: theme, content, size

- ConflictCard
	
    Работает: user, role, status

- ContentLayout
	
    Работает

- DatePicker
	
    Работает: value, isMobile
	
    **Не работает/ ничего не происходит: inline, minDate**
	
    **Нет возможности менять значение: disabled**

- Dialog
	
    Работает: title, isExitButton

	**Ничего не происходит: isConfirmDialog**
	
    **похоже на нарушение логики isAlertDialog и isConfirmDialog**

- DropDown

	**сторя не запускается**

- ErrorDialog
	
    Работает: text

- GradientDivider
	
    Работает

- InfoContainerContent
	
    Работает: name, id, phone, address

- InfoContainer

	Работает: avatar

- Informer
	
    Работает: text

- InputWrapper
	
    Работает: placeholder, inputValue, containerMessages

- LightPopup
	
    Работает: hasCloseButton, isPopupOpen

- Logo
	
    Работает

- MainPopup
	
    Работает: name, phoneNumber, avatarName, avatarLink
	
    **isMobile ничего не отображается**

- MessageCard

	**сторя не запускается**

- Message
	
    Работает: messageText, avatarLink
	
    **type работает все, кроме send.**

- RegistrationNotice

	Работает: settingText

- SmartHeader

	Работает: icon, text

- TimePickerElement
	
    Работает: startTime
	
    **Не работает: isMobile**

____

## Entities

- PopupChat
	
    Работает: messages, isOpen

- TaskList
	
    **сторя не запускается**

- TaskItem

	**сторя не запускается**

- UserInfo
	
    **сторя не запускается**

___

## Features

- Request
	
    **сторя не запускается**

- EditViewerInfo

	Работает: isOpen
	
    **Компонент не берет данные из userAvatar, userName, userPhone, userAddress**

- Filter
	
    **Не работает**
    
---

## Widgets

- PageLayout
	
    **сторя не запускается**

- BalanceSettings
	
    **сторя не запускается**

- ButtonWithModal
	
    Работает: modalContent, closeButton

- Header
	
    Отсутствуют Controls

- SideBar
	
    Работает: links, position

- YandexMap
	
    **сторя не запускается**

- Submenu
	
    **Нет описания style**

- SideMenu
	
    Работает: authRequired, links

- UserCard
	
    **сторя не запускается**
