### ISSUE TITLE
Проверка функционала работы с активной заявкой волонтера по брифу

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#375]
Все ошибки по выбранной роли скидываем в комментарии к этой задаче

**Comment by AnnaBerdik** [comment]
Ссылка на документ "Тестирование функционала по брифу (волонтер). Раздел активные заявки." https://docs.google.com/document/d/1rCGnK03PNKvgcpKGKrQ9EQAO09na7bom6m5UGd7xsrI/edit?usp=sharing
