### ISSUE TITLE
Проверка функционала работы с активной заявкой реципиента по брифу

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#376]
Все ошибки по выбранной роли скидываем в комментарии к этой задаче

**Comment by Elena-Orekhova** [comment]
Тестирование функционала по брифу (роль-реципиент, Активные заявки) представлено в виде таблицы: https://docs.google.com/document/d/1dqJWc01KEBq5gsWV9r2PTOOXZmlV5S2VgIBaP8mOxzM/edit
