### ISSUE TITLE
Исправления модалке создания задачи

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#387]
Ветка - `fix/create-request`
- [x] Первый и второй экраны. Убрать прыжки Error текста. Место под error текст должно быть забито заранее
- [x] Третий экран. Слетели отступы между инпутами + также место под текст ошибки должно быть забронировано.
- [x] Четвертый экран. Если на предыдущем экране выбрана слишком длинная категория, то она некорректно отображается.
Исправить и проверить все остальные категории + ОБЯЗАТЕЛЬНО отобразить разные варианты категорий в сторибуке (CategoriesBackground) https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=3366-8868&t=ZeP1yrcrcVwCxNzY-4
- [x] Четвертый экран. Кнопка "Читать" сейчас отображается даже если текста мало.
- [x] Проверяем общую верстку для всех этапов модалки создания.

⚠ Обязательно проверяем и мобилку, что ничего не сломалось.

- [x] Пока не обязательно к выполнению. Но задача со звездочкой. На первом экране при выборе чекбокса "Бессрочно" календарь должен приобрести неактивное состояние https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=6767-13592&t=ZeP1yrcrcVwCxNzY-4

**Comment by makimaki04** [comment]
@INextYP Саш, привет! по поводу последнего пункта по состояю disabled для календаря. В голову пришел только вариант, при котором необходимо менять ui компонент DatePicker. Есть ли способ решить данную задачу без редактирования ui компонента?

**Comment by INextYP** [comment]
> @INextYP Саш, привет! по поводу последнего пункта по состояю disabled для календаря. В голову пришел только вариант, при котором необходимо менять ui компонент DatePicker. Есть ли способ решить данную задачу без редактирования ui компонента? 

Привет. Самый корректный способ - это сделать правильный UI-компонент, который будет иметь все состояния (активен/ выключен). Если делать disabled state в обход ui-компонента, то это уже явно будет смахивать на костыль.

Важно. Если меняем ui-компонент, то нужно проверить, что ничего не сломалось в местах, где он используется

**Comment by makimaki04** [comment]
Привет! Ссылка на PR: https://github.com/ya-pomogau/frontend/pull/416
