### ISSUE TITLE
Админка. Новый формат чатов

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#388]
Ветка - fix/new-chat-tabs

Задача многоэтапная. Первый этап - рефакторинг общей вёрстки.

Текущие 3 таба "Ждут ответа", "В работе", "Конфликтное закрытие" должны превратиться в "Обращения" и "Конфликты" с дополнительными табами "Нерассмотренные", "В работе" и "Завершенные".

**Comment by Anton-Laid** [comment]
Сейчас сижу с телефона и чтобы ничего не сломать, пишу здесь. Возьму задачу себе.

**Comment by Elena-Orekhova** [comment]
https://github.com/ya-pomogau/frontend/pull/424
