### ISSUE TITLE
Доработки по BalanceSettings

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#395]
Ветка для работы - refactor/balance-settings

**В компоненте BalanceSettings**
- [x] Убрать интерфейс `BalanceSettingsProps` и пропс в `BalanceSettings` компоненте.
- [x] Избавиться от использования библиотеки `classnames` в этом компоненте
- [x] Избавиться от `usePermission` в этом компоненте. Пользователь без необходимых разрешений итак не попадает на эту страницу
- [x] Очистить неиспользуемые импорты

**В компоненте BidsPage**
- [x] Убрать лишнюю обертку div

**В компоненте BalanceSettingsItem**
- [x] В папке с компонентом создать файл `styles.module.css` и перенести в него стили, которые относятся к BalanceSettingsItem и его элементам
- [x] Для селектора balance_text использовать шрифт из переменной. Вот это:
```
className={classnames(
            styles.balance_text,
            'text',
            'text_size_medium',
            'm-0',
            'p-0'
          )}
```
Должно превратиться в это:
```
className={styles.balance_text}
```
- [x] Избавиться от использования библиотеки `classnames` в этом компоненте
- [x] Заменить <BallsIcon color="blue" size="46" /> на <Icon icon="BallsIcon" color="blue" size="46" />
Итоговый очищенный компонент должен выглядеть так:
```tsx

import { ChangeEvent } from 'react';

import { Input, Icon } from 'shared/ui';

import styles from '../styles.module.css';

interface BalanceSettingsItemProps {
  title: string;
  inputValue: number;
  handleChange: (e: ChangeEvent<HTMLInputElement>) => void;
}

const BalanceSettingsItem = ({
  title,
  inputValue,
  handleChange,
}: BalanceSettingsItemProps) => {
  return (
    <div className={styles.balance_box}>
      <p className={styles.balance_text}>{title}</p>
      <Input
        className={styles.balance_input}
        defaultValue={inputValue}
        name={title}
        onChange={handleChange}
        type="number"
        min="1"
        step="1"
      />
      <Icon icon="BallsIcon" color="blue" size="46" />
    </div>
  );
};
```

⚠ Не забываем проверить, что мобильное разрешение не сломалось.

**В файлах стилей компонентов, с которыми работем**
- [x] Проверить, что все селекторы явно используются в компонентах
- [x] Пройтись по стилям и проверить, что все явно требуются для корректного отображения
- [x] Все цвета должны браться из css переменных
- [x] Все шрифты должны браться из css переменных. Вместо этого:
```css
font-family: Golos;
  font-size: 12px;
  font-weight: 400;
  line-height: 17px;
```

Должно быть так:
```
font: var(--перемененная)
```

**Comment by KuzmichevaES** [comment]
@IgorVPav Добрый вечер! У меня пропал доступ к пачке в чаты Я помогаю. Можешь, пож-та, посмотреть?

**Comment by IgorVPav** [comment]
Привет!) Выясняю, я тебя не исключал. Если что - добавлю снова, не
переживай)

вт, 3 сент. 2024 г. в 18:24, KuzmichevaES ***@***.***>:

**Comment by IgorVPav** [comment]
Из админов никто тебя не удалял. Возможно это ошибка из-за того, что ты
закончила обучение или перепутали с кем-то. Напиши в поддержку или
куратору, объясни ситуацию и попроси восстановить тебя во всех чатах
Я_Помогаю. Не получится- пиши.)

вт, 3 сент. 2024 г. в 18:24, KuzmichevaES ***@***.***>:
