### ISSUE TITLE
Реализовать страницу заблокированного пользователя

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#404]
feat/blocked-user-page

В рамках задачи необходимо реализовать страницу заблокированного пользователя.

По роуту /pick такие пользователи уже есть.

Пока что необходимо сделать решение "по-своему". В дальнейшем будем улучшать

**Comment by zmdog** [comment]
Я могу вместе с созданием страницы заблокированного пользователя, объединить ошибки подключения к интернету и блокировку пользователя в одну? контент похож

**Comment by zmdog** [comment]
и еще вопрос по макету. может центрировать по высоте?

![Image](https://github.com/user-attachments/assets/7ab131c5-5335-4f2b-927f-5080e0446084)
