### ISSUE TITLE
Восстановление упавших Story в Сторибуке

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#405]
fix/storybook-stage-1

**FormElements**

Checkbox

- [x] defaultChecked: boolean - изменение значения ничего не меняет

проблема заключается в том, что свойство defaultChecked не обрабатывается корректно в компоненте Checkbox `src/shared/ui/checkbox/index.tsx` В файле checkbox/index.tsx нет никакого кода, который бы обрабатывал изменение значения `defaultChecked`.

Чтобы исправить эту проблему, нужно добавить код, который будет обрабатывать изменение значения `defaultChecked` и обновлять состояние флажка соответствующим образом.

Fieldset

- [x] view - работает в примерах, но не работает при изменении значения в сторибуке.
проблемы с работой функции представления в Fieldset src/shared/ui/fieldset/index. tsx

используется свойство представления в Fieldset :14:0-35:2 .

const Fieldset = ({
  title,
  view = FieldsetView.COLUMN,
  children,
  ...props
}: FieldsetProps) => (
  <fieldset {...props} className={styles.fieldset}>
    <legend...
    >
      {title}
    </legend>
    <div className={styles.content} data-view={view}>
      {children}
    </div>
  </fieldset>
);
как видно не используется свойство view для изменения расположения дочерних элементов, просто добавляется атрибут просмотра данных к элементу div. Нужно добавить св-во добавления дочерних элементов

- [x] InputAddress сторя не запускается `src\shared\ui\input-address\index.tsx`. Cторибук не видит этот элемент потому что отсутствует его контекст

- [x] InputPhone
ошибка некорректного номера телефона отображается без error true
src\shared\ui\form-input-phone\index.tsx
ошибка в валидации MaskedInput , react-hook-form автоматически валидирует ввод и отображает сообщение об ошибке, когда ввод не является валидным.

-[ ] Input

проблемы с версткой customIcon исправление верстки

- [x] Select

Не работает: placeholder, error
src\shared\ui\select\select.stories.ts

в файле стора отсутствуют эти пропсы их надо добавить

не отображается placeholder, выбранный элемент

**Comment by Elena-Orekhova** [comment]
https://github.com/ya-pomogau/frontend/pull/420
