### ISSUE TITLE
Доработка стори в Сторибуке (Button, SquareButton, Tooltip)

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#406]
fix/storybook-stage-2

- [x] Button

Нет возможности проверить: actionType
добавить в стор для actionType 
'submit' | 'reset' | 'button'
isLoading - лоудер отображается за пределами кнопки
в файле src\shared\ui\button\index.tsx обновить логику отображения лоадера можно как на примере и проверить стили: для заблокированного состояния у кнопки и стили лоадера

⚠ Если в дизайне нет кнопки с лоудером, то выпиливаем вообще эту логику

- [x] SquareButton

disabledColor: boolean - проверить дизайн, если у нас есть кнопки с выключенным цветом иконки, то оставить, иначе - убрать

есть незадокументированное свойство taskId. Это бизнес логика, за которую компонент не должен отвечать

- [ ] Tooltip

Не описаны возможные значения pointerPosition. Изменение значения на right ни к чему не приводит
обновить соответствующие стили и логику в UI-компоненте. Проверить использование компонента во всех местах и доисправить если требуется.
src/shared/ui/tooltip/index.tsx:
после чего обновить файл стора

**Comment by KuzmichevaES** [comment]
Привет! @INextYP 
Button:
По "Нет возможности проверить: "actionType" - добавила в argTypes (не уверена, правильно ли).
Также в некоторых местах компонент Button вызывается и тип ему передается не пропсом actionType, а сразу через type - пример: ![Image](https://github.com/user-attachments/assets/58581c85-66f9-44c0-9274-b9eb138c9a99)

Нужно ли это поправить, чтобы всё передавалось через пропсы?

На макете кнопки с лоадером нет, поэтому логику удалила.

SquaryButton:
В макете кнопки с выключенном цветом иконки есть, taskId удалила.

По поводу Tooltip и pointerPosition - логика в компоненте рабочая (уголок смещается влево, если расстояние от левого края меньше, чем сам Tooltip), в стори расположение уголка компонента всегда слева, т.к расстояние слева всегда меньше, чем Tooltip и всегда срабатывает логика. Попыталась через декоратор обернуть стори defolt в див с отступами, чтобы увеличить расстояние, но выкидывает ошибки типизации.
Совсем закопалась в этих стори, можешь, пож-та, подсказать - декоратором же можно сделать необходимые отступы по краям, чтобы логика компонента срабатывала? Или может еще есть какой-то способ сделать доп настройку, чтобы поменять расстояние от левого края?
