### ISSUE TITLE
Проверка функционала главного админа по брифу

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#409]
В рамках задачи необходимо проверить функционал главного админа по брифа и предоставить отчет в формате:
<такой-то-пункт> - работает или нет логики такого-то...

Код писать не нужно (можно в качестве playground`a чтобы понять и описать, что нужно починить для исправления такого-то пункта)

**Comment by gavr90** [comment]
Отчет приложен. Прошу поправить, если необходим отчет в ином формате, либо есть замечания по содержанию.
[Отчет задача 409 главный администратор.docx](https://github.com/user-attachments/files/16875659/409.docx)
