### ISSUE TITLE
Синхронизировать типы для чата

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#413]
Ветка для работы - `fix/chats-types`

В рамках задачи нужно выполнить синхронизацию типов чата на фронтенде с бекендом. 
Пока что ориентируемся на тип чатов между реципиентом и волонтером И между пользователем и админом.

**Comment by Gottgunst** [comment]
@INextYP  речь идёт о типизации и согласовании интерфейсов Message?
на фронте нашёл:
```
export interface IMessage {
  id: number;
  userId: string;
  userAvatarLink: string;
  message: string;
  date: Date;
}
```
а на бэке:

```
export interface MessageInterface {
  _id: ObjectId;
  title: string;
  body: string;
  attaches: string[];
  createdAt: Date;
  author: AnyUserInterface;
  chatId: ObjectId;
}
```

или есть отдельные типы для чатов?

**Comment by INextYP** [comment]
Привет. Напиши в пачку в канале. Женя покажет актуальные типы
