### ISSUE TITLE
Исправить падение приложения при обновления данных о профиле

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#429]
Ветка для работы: `bugfix/update-user-profile`

При обновления профиля сейчас вылетает ошибка:

![Image](https://github.com/user-attachments/assets/e2cb7201-cb68-4efa-a8f8-e5abf84341bc)

В рамках задачи необходимо найти и устранить причину.

**Comment by AlexandraSukhova** [comment]
Если я правильно поняла логику работы закоментированной строки, то в варианте ниже при обновлении данных пользователя сайт не падает, ошибка была из-за невозможности итерировать объект ![Image](https://github.com/user-attachments/assets/3d09efbf-0f0b-43ed-8d1f-1530df49ce79)
