### ISSUE TITLE
Реципиент. Создание заявки. фикс верстки и логики. Экран выбора места

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#455]
Ветка для работы - fix/create-task-stage-2

В рамках задачи необходимо подправить вёрстку модалки создания задачи у реципиента на мобильном разрешении только для указанного шага.

Сейчас выглядит всё так:

![Image](https://github.com/user-attachments/assets/08839ca4-f421-4c1e-95e5-2b3301a46a05)

Что нужно сделать:

- [x] Подогнать вёрстку под дизайн. (ссылка)[https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=7169-22809&t=geDwdV239ZrToNNP-4]. Важно - кнопку "крестик" и инпут с адресом оставляем так как есть - это согласовано с заказчиком
- [x] Проверить, что на декстопном разрешении ничего не полетело
- [x] Задача по логике: нужно чтобы при нажатии на карте балун автоматом переместился на эту точку (сейчас его можно только вручную перенести)

**Comment by makimaki04** [comment]
@INextYP Привет! Ссылка на PR: https://github.com/ya-pomogau/frontend/pull/483
