### ISSUE TITLE
Фикс верстки и логике в карточке задачи

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#457]
Ветка для работы - fix/task-card-logic

В рамках задачи необходимо проверить и исправить вёрстку для карточки задачи.

Для мобилки явно сейчас не совпадает:

![Image](https://github.com/user-attachments/assets/99bc05bc-1c3e-4d1f-886e-ec89b6f924a1)

- [ ] Проверено мобильное разрешение карточки
- [ ] Проверено декстопное разрешение карточки

При нажатии на иконку телефона (если волонтер назначен) сейчас отображается номер телефона, который прописан в коде

![Image](https://github.com/user-attachments/assets/9331d5b8-984b-4bc1-95d1-c77e8a93d38f)

а нужно, чтобы отображался номер соответствующего исполнителя/ реципиента

**Comment by Varikash** [comment]
@INextYP я правильно понимаю, что претензия в плане верстки идёт относительно иконок ? https://prnt.sc/Jgx4vxw0JcHv
Потому что в остальном я проблем не вижу сейчас. Номер подправил вроде.
