### ISSUE TITLE
Перенос типов для конфликтных чатов; Исправление отображения; Настройка логики

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#473]
Ветка для работы: `fix/conflict-chat-types`

В рамках задачи необходимо;

- [x] Перенести типы для конфликтных чатов
- [x] Исправить раздел "чат" у администратора. В разделе обращения должны отображаться моковые сообщения (не конфликтные)
- [x] В разделе "конфликты" должны отображаться моковые конфликты
- [x] При переключении между табами пока выводим в консоль "название раздела - название подраздела", например, если мы зашли в задел "конфликты" и в подраздел "закрытые", то в консоль выведется сообщение "мы в разделе конфликты, подразделе закрытые". Это нужно чтобы правильно определять логику в дальнейшем.
- [x] Проверить отображение. Вот такого быть не должно:
![Image](https://github.com/user-attachments/assets/fb1e1142-a95a-4327-aaef-e209f579f10b)

**Comment by Gottgunst** [comment]
@INextYP  Первую неделю я проболел, сейчас вроде прихожу в себя, и надеюсь, что за вторую неделю успею выполнить хотя бы часть задачи.

**Comment by Gottgunst** [comment]
![image](https://github.com/user-attachments/assets/4159ccae-c27d-46f0-b520-b171d3dd72e4)
Для чего планировалась страница `section-chat-hub` ?
Сейчас, `SectionChatHub` нигде не задействована в макете.
