### ISSUE TITLE
Декомпозиция `Mark` и ``UserMark`` компонентов

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#486]
Ветка для работы: `fix/mark-and-usermark-components`

В рамках задачи работаем исключительно с компонентами `Mark` и `UserMark`.

Что необходимо сделать:

- [x] Выносим все `svg` иконки в переменные с максимально понятным названием. Можно в директории `map` создать файл `icons.ts` и в нём хранить все эти переменные. 
- [x] Вставляем эти переменные на места, где эти свгшки использовались. Обязательно обращаем внимание на то, что некоторые свгшки отличаются только цветом. В таком случае пишем функцию, которая в зависимости от переданного параметра вернет свг с нужным цветом.
- [x] После выполнения предыдущих действий вот этот участок кода:
![Image](https://github.com/user-attachments/assets/3659c317-167b-4542-b6b2-acb961ff2346)
должен превратиться примерно в такую вариацию:

```ts
<div class="mark_container">
   // вот тут будет вызвана функция, в которую нужно передать `properties.isUrgentTask` и которая вернет свгшку с нужным цветом
</div>
```

Соответственно, `{% if properties.isUrgentTask %}` и `{% else %}` и `{% endif %}` не понадобятся.

- [x] `Balloonlayout` аналогично пытаемся сократить самостоятельно

- [ ] Задача со звездочкой. Выполнять по желанию, но если сделаешь, будет круто.
Необходимо избавиться от вот этих строк в обоих компонентах и написать кастомную типизацию, чтобы не было ошибок.
![Image](https://github.com/user-attachments/assets/07baf1e8-71f2-47b5-a405-2354d167e98b)

**Comment by AlinaBrode** [comment]
Взялись за тесты. В ветке development тесты падают. Разберусь с тем, почему падают и попробую починить. Покрою свой код тестами.
