### ISSUE TITLE
Исправить баг с обновлением данных профиля + фикс кнопки

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#521]
Ветка для работы: `fix/update-profile`

В рамках задачи необходимо:

- [x] Проверить, почему после обновления данных профиля показывается вот это:
![Image](https://github.com/user-attachments/assets/5e1b86d8-d01d-426d-8429-45d8e204d769)

- [x] Убрать обводку кнопки (появляется если на открытой модалке редактирования профиля нажать ESC)
![Image](https://github.com/user-attachments/assets/66c198fb-bfca-4153-95b5-dd1fe95ed23f)

После обновления страницы всё работает как надо.

**Comment by Elena-Orekhova** [comment]
https://github.com/ya-pomogau/frontend/pull/550
