### ISSUE TITLE
[New]Работа с интерфейсами чатов. Подстроить модель данных чатов в компонентах к актуальной

### ISSUE THREAD

**Issue by VladislavSerKir** [ya-pomogau/frontend#70]
Необходимо выполнить подстроку пропсов и стора в компонентах к текущей согласованной модели данных
![2023-11-02_20-06-05](https://github.com/ya-pomogau/frontend/assets/83783362/7cab8baa-b9f3-46d5-8d93-8fba69c4de71)

**Comment by kspshnik** [comment]
**Внимание!** Эта модель *не актуализована*

В реальности должны быть *три разных* модели, которые будут жить в дискриминированной коллекции.

**Comment by kspshnik** [comment]
Реализация модели на фронте до устаканивания на бэкенде представляется преждевременной.

**Comment by kspshnik** [comment]
Модель разрабатывается в рамках других задач, и по другой модели на бэкенде.
