### ISSUE TITLE
blog-page 

### ISSUE THREAD

**Issue by kspshnik** [ya-pomogau/frontend#87]
Создать страницы блога для пользователя и администратора как для настольной так и для мобильной версии. Вёрстка должна быть максимально адаптивной.

**Comment by kspshnik** [comment]
@margo-yunanova а зачем? задача-то выполнена, это было автоматичческое закрытие.

**Comment by margo-yunanova** [comment]
> @margo-yunanova а зачем? задача-то выполнена, это было автоматичческое закрытие.

@kspshnik , задача не выполнена, нужно сделать страницу, а  это только один компонент.
Нужно сделать ещё форму и компонент, который будет управлять постами и формой.

**Comment by kspshnik** [comment]
Принято. Тогда лучше не делать PR в `develop`, пока полностью не готово.
Я восстановил твою ветку `feature/blog-post` - дальше, делай от неё новые подветочки и PR уже в эту веточку, а в `develop` - только когда уже **всё** будет готово, хорошо?
