### ISSUE TITLE
Функционал реципиента, схема вариантов использования

### ISSUE THREAD

**Issue by marussia1996** [ya-pomogau/frontend#96]
Нарисовать на доске miro схему, описывающую варианты использования для реципиента. Проверить функционал реципиента на работу.

**Comment by kspshnik** [comment]
Опиши пожалуйста полноценно проблему.

**Comment by INextYP** [comment]
- [x]  1. Если пользователь зарегистрировался, но не активирован администратором/ главным администратором, должна отображаться надпись над активными заявками - Спасибо за регистрацию. Как только администратор подтвердит Вашу учетную запись, Вы сможете создавать заявки. Также, визуальная составляющая НЕактивированного аккаунта должна соответствовать дизайну (серый плюс, при нажатии на который появляется модалка - Вы пока не можете создавать заявку. Дождитесь подтверждения администратора)

- [x]  2. Раздел активные заявки. Проверить все соответствия дизайну и брифу, кроме чатов, его пока не трогаем. Можно сделать, чтобы при нажатии на иконку чата, открывался чат, но функциональность его прорабатывать пока не нужно.

    - [x] 2.1. Создание заявки. Время назначения заявки не должно быть меньше текущего и должно быть обязательно заполнено (сделать валидацию)
    - [x] 2.2. Создание заявки. При установлении чекбокса "бессрочно" календарь и timepicker должны становиться неактивными.
    - [x] 2.3. Создание заявки. Шаг "Укажите место встречи". Возможно 2 варианта - или пользователь выбирает точку на карте (изначально метка должна показывать местоположение реципиента на основании адреса, указанного при регистрации) (инпут должен заполниться автоматом) или реципиент вводит в инпут полный адрес (просто город не подойдет, обязательно должны быть все элементы, включая улицу и дом (хотя бы примерно))
    - [x] 2.4. Создание заявки. Шаг "Выберите тип задачи". Тип задачи - обязательное поле, описание предлагаю сделать также обязательным, хотя бы 5 символов. Также, не забываем, про ограничение в 300 символов. Пока хотя бы один из инпутов не заполнен - на следующий шаг не пропускаем.
    - [x] 2.5. Создание заявки. Завершающий шаг - сделать отображение согласно дизайна и проверить на корректность.
    - [x] 2.6. Создание заявки. Этап закрытия попапа. Если реципиент закрывает попап на крестик или на оверлей, то должна отобраться модалка "Закрыть окно сейчас и удалить ранее внесенную информацию?", где он может выбрать "Закрыть" - и данные формы удалятся ИЛИ "Вернуться" (кнопки в дизайне нет, но стоит прикрутить её рядом с "Закрыть") - и данные вернуться и пользователь останется в форме на прежнем месте.
- [x] 3. Раздел активные заявки. Редактирование заявки. Всё должно работать аналогичным образом как и при создании заявки. Рядом с каждым полем должен находиться "Карандаш" с описанием, что он редактирует, при нажатии на него должна отображаться форма с предзаполненными данными, доступными для редактирования.
- [x] 4. Раздел активные заявки. Фильтрация. Должна быть работоспособной и отобрать только нужные данные в соответствии с фильтром. При этом, если фильтр применен, то разумнее было бы отображать хоть какую-то точку на иконке фильтра (чтобы пользовать понимал, что фильтр применен). При нажатии на "Сбросить фильтры" - фильтр сбрасывается.
- [x] 5. Раздел активные заявки. Редактирование заявки. Обязательная проверка на то, была ли заявка взята волонтером или нет. Если да- то редактировать заявку возможно только администратором (реципиенту при этом нужно показывать соответствующую модалку).
- [x] 6. Раздел "Завершенные заявки". Проверить и настроить кликабельность всех элементов страницы, а также отображение всех модалок в соответствии  с дизайном. Настроить работу фильтров.
- [ ] 7. Написанный функционал должен быть подкреплен тестами!!!
