### ISSUE TITLE
Функционал волонтера, схема вариантов использования

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#97]
Задачи для страницы волонтера + карта

- [x] #102
- [x] 2. На основании адреса, указанного при регистрации волонтера на карте должен отображаться маркер с дефолтным радиусом.
- [x] 3. При изменении радиуса в фильтрах, должен изменяться масштаб карты.
- [x] 4. При изменении даты и/ или времени в фильтрах, на карте должны отображаться только метки, которые соответствуют фильтру. Категории пока не трогаем.
- [x] #108
- [x] #103
   - [x] 6.1: "Галочка" - при начатии отображается модалка "Благодарим за отзывчивость"
    - [x] 6.2: "Восклицательный знак и крестик" - при нажатии происходит 1 из 3-х возможных кейсов по возможности/ невозможности отмены заявки, т.е, или пользователь не может отменить заявку или подтвердить, что заявка не выполнена или отмена с указанием причины отмены.
    - [x] 6.3: "Телефонная трубка" - при нажатии (если пользователь зашел с телефона) должен происходить звонок реципиенту. Если волонтер не с мобильного устройства можно просто отображать номер реципиента в виде выпадающего меню (при повторном нажатии номер должен скрываться)
- [x] #113
- [x] #114
    - [x] 8.1. "Галочка" - в дизайне кейс не указан, но при наведении или нажатии на неё предлагаю отображать дату и время завершения заявки
    - [x] 8.2. "Восклицательный знак" - статус заявки (выполнена или не выполнена). Цвет также должен варьироваться в зависимости от статуса
    - [x] 8.3. По номеру телефон аналогичный кейс, как и в 6.3.
- [x] #116
- [ ] 10. Написанный функционал должен быть подкреплен тестами!!!
Все данные пока что формируем в моковом варианте, продумывая все возможные кейсы и фильтрации. Главный исход - максимально приближенно подготовить весь функционал для подключения бека.

**Comment by ulbee** [comment]
>  1. Если пользователь зарегистрировался, но не активирован администратором/ главным администратором, должна отображаться надпись над картой заявок (Спасибо за регистрацию. Как только амнинистратор подтвердит Вашу учетную запись, Вы сможете откликаться на заявки.). Даже если пользователь попытается нажать на "отлкликнуться" на карте (но аккаунт ещё не подтвержден), должна отобраться надпись "Вы пока не можете откликнуться на заявку. Дождитесь подтверждения администратора".

У такого пользователя какое именно значение в поле status? В моках есть волонтер со статусом `verified`, хочу добавить еще не активированного волонтера

**Comment by kspshnik** [comment]
> > 1. Если пользователь зарегистрировался, но не активирован администратором/ главным администратором, должна отображаться надпись над картой заявок (Спасибо за регистрацию. Как только амнинистратор подтвердит Вашу учетную запись, Вы сможете откликаться на заявки.). Даже если пользователь попытается нажать на "отлкликнуться" на карте (но аккаунт ещё не подтвержден), должна отобраться надпись "Вы пока не можете откликнуться на заявку. Дождитесь подтверждения администратора".
> 
> У такого пользователя какое именно значение в поле status? В моках есть волонтер со статусом `verified`, хочу добавить еще не активированного волонтера

_src/shared/types/common/types.ts_ :
```ts
export enum UserStatus {
  UNCONFIRMED = 0,
  CONFIRMED = 1,
  VERIFIED = 2,
  ACTIVATED = 3,
}
```

Как ты думаешь, какой из этих статусов соответствует не подтверждённому пользователю? :)

**Comment by ulbee** [comment]
> Как ты думаешь, какой из этих статусов соответствует не подтверждённому пользователю? :)

наверное  `UNCONFIRMED`? =))
там так много всего, найти эти типы без подсказки было невозможно) спасибо
