### ISSUE TITLE
Функционал администратора/ главного администратора, схема вариантов использования

### ISSUE THREAD

**Issue by INextYP** [ya-pomogau/frontend#98]
Администратор и главный администратор (специфика функционала по подтверждению аккаунтов у них практически повторяется, так что и задачи в одном стеке):

- [ ]  1. На текущий момент у нас пока нет полноценной страницы для входа обычного администратора, только через /pick
- [x] 2. Если у обычного администратора нет прав на подтверждение/ блокировку и т.д., то не давать ему это сделать (можно создать мокового админа и поэкспериментировать с ним)
- [x] 3. На табах должен отображаться счетчик с количеством элементов в том или ином табе по которым необходимо совершить действие
- [ ] 4. Некорректно работает поиск по имени;
- [ ] 5. Не работает функция позвонить и написать волонтеру/ реципиенту
- [x] 6. Настроить визуал кнопок согласно дизайну
- [ ] 7. Настройка раздела "не обработанные". В этом разделе должны лежать все новые аккаунты, которые ещё не подтверждены. Администратор может выполнить нужный сценарий: “Подтверждение / Блокировка статуса волонтера” или “Подтверждение / Блокировка статуса реципиента”. После первичного действия карточка пользователя отображается только в разделе соответствующем его роли.
- [ ] 8. Настроить этапы подтверждения аккаунтов главным администратором/ администратором согласно Ноушена (прошу обратить на это особое внимание, т.к. у волонтера аккаунт подтверждается по одному сценарию, у реципиента по-другому и т.д.)
- [ ] 9. Настроить функционал выдачи ключей волонтерам;
- [ ] 10. Настроить функционал блокировки аккаунтов;
- [ ] 11. Написанный функционал должен быть подкреплен тестами!!!
Важно! Раздел статистики и раздел "заявки/ работа с заявками" пока не трогаем!!! Сейчас, самое главное, чтобы после подключения бекенда и регистрации новых пользователей (реципиента и волонтера) - администратор подтвердил их данные и они могли смело пойти и взять/ создать заявку.

**Comment by lexanikitin** [comment]
Мое видение задач, приглашаю к дискуссии с целью разбиения задач до атомарных и понятных подзадач  : 
1. Разумно использовать страницы /login для входа как супера так и администратора , в зависимости от введенной пары пользователь получит свои права, и переходит на свою страничку?

2. Получаем из карточки администратора набор его прав. Далее в коде элементов страницы проверяем наличие прав на действия и деактивируем запрещенные элементы интерфейса. Дублирующая проверка прав на действие должна быть на стороне бекенда.

3. Кажется чтото похожее делалось ранее в бургерном учебном проекте 

4. Надо анализировать

5. Кнопка позвонить реализует вызов звонилки по-умолчанию, для этого ссылка формата "tel:+123456789" ?
C функцией написать есть вопрос - написать где , на нашем сайте (вроед нету такой возможности), ссылка может вызывать написание нового письма , если у пользователя в карточке есть email который мы можем выставить в ссылку. Надо подчитать документацию проекта.

6. Изучать макет

**Comment by lexanikitin** [comment]
5. Кнопка позвонить реализует вызов звонилки по-умолчанию, ждя этого сссылка формата "tel:+123456789"

**Comment by kspshnik** [comment]
> Вопросы по пунктам задания :
> 
> 1. Разумно использовать страницы /login для входа как супера так и администратора , в зависимости от введенной пары пользователь получит свои права, 

Так и надо, роль `Master` (Главный администратор) отличается одним флажком в объекте пользователя: `isRoot`, у рута он натурально `true`.

Ну и вытекающими из этого правами и полномочиями... :)

**Comment by kspshnik** [comment]
> и переходит на свою страничку?

Дак она одна и та же. Дальше всё регулируется наличием полномочий у админов, они у них могут отличаться друг от друга :)

**Comment by lexanikitin** [comment]
> > и переходит на свою страничку?
> 
> Дак она одна и та же. Дальше всё регулируется наличием полномочий у админов, они у них могут отличаться друг от друга :)

тогда я не очень понял смысл первого задания. по сути задание дальше , следующее, ограничивать действия по выставленным правам

**Comment by kspshnik** [comment]
> тогда я не очень понял смысл первого задания. по сути задание дальше , следующее, ограничивать действия по выставленным правам

Но странички-то не отдельные :) Мы показываем или нет отдельный функционал, но это одна и та же `page`. Зачем плодить сущности?

**Comment by lexanikitin** [comment]
это то как раз логично , плодить нет нужды. 1 и 2 задачи очень взаимосвязаны , надо сделать разных админов моковых и супера (уже есть) и в зависимости от прав и уровня настроить странички под них.

**Comment by lexanikitin** [comment]
Для 5 задачи предлагаю использовать звонилку с вставкой номера телефона "tel:+712345678" 
А для сообщения - открывать диалог в ВК (мы знаем пользователя Вк при регистрации) по сути тоже ссылка со вставкой данных из карточки

**Comment by lexanikitin** [comment]
Для 5 задачи предлагаю использовать звонилку с вставкой номера телефона "tel:+712345678" 
А для сообщения - открывать диалог в ВК (мы знаем пользователя Вк при регистрации) по сути тоже ссылка со вставкой данных из карточки

**Comment by kspshnik** [comment]
> Для 5 задачи предлагаю использовать звонилку с вставкой номера телефона "tel:+712345678" А для сообщения - открывать диалог в ВК (мы знаем пользователя Вк при регистрации) по сути тоже ссылка со вставкой данных из карточки

Не, если мобилка - то инициируем звонок прям, а для десктопа показываем номер в тултипе вроде.
@INextYP так же?

А сообщения - это _внутренний_ чат, никакого ВК (которого у админа может аще не быть)

**Comment by INextYP** [comment]
> > Для 5 задачи предлагаю использовать звонилку с вставкой номера телефона "tel:+712345678" А для сообщения - открывать диалог в ВК (мы знаем пользователя Вк при регистрации) по сути тоже ссылка со вставкой данных из карточки
> 
> Не, если мобилка - то инициируем звонок прям, а для десктопа показываем номер в тултипе вроде.
> @INextYP так же?
> 
> А сообщения - это _внутренний_ чат, никакого ВК (которого у админа может аще не быть)

Да, верно Жень, именно по такому кейсу действуем. Вк нужен только для регистрации. Функциональности внедрения месседжера из ВК точно не планируется, да и лишнее это будет.

**Comment by SergeyKukhtalevV** [comment]
Добрый вечер!
Подскажите, нам нужно менять страницу авторизации, чтобы соответствовало макету? 
![image](https://github.com/ya-pomogau/frontend/assets/106655509/626a6173-3ac7-45c6-a9ee-7e0fccec001e)

**Comment by SergeyKukhtalevV** [comment]
Подскажите, нам нужно менять страницу авторизации, чтобы она соответствовала макету?
![image](https://github.com/ya-pomogau/frontend/assets/106655509/bfe04c03-2fb7-418d-b5f2-0ce5934deecc)

**Comment by kspshnik** [comment]
> Подскажите, нам нужно менять страницу авторизации, чтобы она соответствовала макету?

Нет, макет изменён по согласованию с заказчиком. Изначальный макет был сделан с ошибкой в части неверного понимания процесса логина в ВК.

**Comment by lexanikitin** [comment]
Задача 3 , про счетчики на табах. Прошу поправить если моя мысль гдето уйдет неправильно . 

В имеющемся коде массивы с данными для карточек , из которых мы выделяем те, где необходимы действия получаются на страницах где они же и отображаются. Соответственно счетчик уже бесполезен. 

Копирую получение данных выше в компонент где отображаются табы и там перечитываю и отображаю счетчики прокидывая пропсы внутрь компонентов. Таким образом дублирую запрос на получение данных. 

Либо прокидываю и данные в компоненты ниже для отображения карточек. Удаляя его из места где он сейчас. Тогда запрос один на все данные и их раскидываем.

**Comment by lexanikitin** [comment]
По моей логике стоило делать табы и уже внутри них компоненты областей с отображением данных . У нас же разные страницы на которых отображаются табы. 

тогда на странице одной уже подгружать данные для всех табов, отображая все счетчики

**Comment by kspshnik** [comment]
Можно применить композицию так, чтобы табы и текущее отображение были вложены в один и тот же компонент. Тогда счётчик пробрасываем пропсом (примитивным значением!) и показываем в компоненте таба.
Вспоминаем оборачивать табы в `React.memo()` ибо нечего им всем перерендериваться в каждый чихпых.

**Comment by lexanikitin** [comment]
Задача 4. Некорректная работа поиска. 

Не смог воспроизвести некорректность. Вроде находит по любой части ФИО. Можно подробнее проблему раскрыть ?

**Comment by SergeyKukhtalevV** [comment]
Задача 6. Настроить визуал кнопок согласно дизайну.
Какие кнопки имеется ввиду? На сайд-баре? Расположение строки поиска, карточек пользователей, табов? 
Какой степени соответствия нужно добиться?
![image](https://github.com/ya-pomogau/frontend/assets/106655509/10b308b0-302b-4891-8586-0c55ac210a1f)

**Comment by kspshnik** [comment]
> Какой степени соответствия нужно добиться?

В _идеале_ - РР :)

**Comment by lexanikitin** [comment]
@kspshnik 
Вопрос по табам. У нас в роутере прописаны адреса для все табов. Т.е. открытый таб отражается в адресной строке именно в адресе ,а не в параметре запроса . Сохраняем ? 

Вопрос в механизме листать вкладки , если как сейчас, то нажатие на др вкладку это ссылка и открытие новой страницы с перезапросом данных. Хочется не пераспрашивать апи лишний раз, поэтому могу заменить ссылки сеттерами и менять табы по ним, перерисовывая только то, что нужно.
Плюсом избавимся от нескольких компонентов в проекте.

Тогда и текущий таб я бы поместил в путь в виде параметра в гет запросе ?tab=volunteer

**Comment by lexanikitin** [comment]
@kspshnik
@INextYP

Как сделать вызов чата с пользователем ? Есть интерфейс функционала или пока обойтись сообщением в консоль про кнопке открытия чата ?

**Comment by kspshnik** [comment]
> @kspshnik Вопрос по табам. У нас в роутере прописаны адреса для все табов. Т.е. открытый таб отражается в адресной строке именно в адресе ,а не в параметре запроса . Сохраняем ?


Если поднять хук из RTK на верхний уровень, и грамотно использовать `<Outlet>`, то нет проблем рутить, кмк.

@INextYP ?

**Comment by kspshnik** [comment]
> @kspshnik @INextYP
> 
> Как сделать вызов чата с пользователем ? Есть интерфейс функционала или пока обойтись сообщением в консоль про кнопке открытия чата ?


Думаю, пока да.

@INextYP ? @marussia1996 ?

**Comment by lexanikitin** [comment]
@kspshnik 
@INextYP
для п.п. 7-10 - поясни что имеется ввиду? Кнопочки нажимаются , обработчики нажатий есть , но сейчас это просто сообщения в консоль. Далее туда надо вставить команды работы с апи, через посредников, т.к. именно там находится бизнес логика и там должно происходить изменение свойств. В чем задача сейчас ?

**Comment by kspshnik** [comment]
> для п.п. 7-10 - поясни что имеется ввиду? Кнопочки нажимаются , обработчики нажатий есть , но сейчас это просто сообщения в консоль. 

Я предполагаю, в написании соответствующих мутаций для RTQ.

@INextYP ?

**Comment by lexanikitin** [comment]
@kspshnik
подсвети, где схема данных, чтобы я понимал что и в каком виде надо

**Comment by lexanikitin** [comment]
@kspshnik 
Нужны подробности и пояснения по мутациям. 
Не могу найти инфо по работе апи, как вообще будем изменять данные , да и как получать. 
Как разделили на слайсы ? в коде увидел только систем слайс с пользователем.

**Comment by kspshnik** [comment]
Подробности называются Redux Toolkit Query ;o)
Есть в официальной доке.

**Comment by lexanikitin** [comment]
@kspshnik
@INextYP 
Задача 4. В чем некорректность ? Опишите проблемный кейс. Протестил, все работает.

**Comment by lexanikitin** [comment]
> Подробности называются Redux Toolkit Query ;o) Есть в официальной доке.

Пытаться перепиливать user-api в UsersSlice ? или это лучше отдельно ?

**Comment by kspshnik** [comment]
> Пытаться перепиливать user-api в UsersSlice ? или это лучше отдельно ?

Нет, это не трогай: там танк отрабатывает норм, его подхватывает слайс, обслуживающий сущность.

**Comment by kspshnik** [comment]
> > Пытаться перепиливать user-api в UsersSlice ? или это лучше отдельно ?

Кросевое будем делать позже, как MVP заработать :)

**Comment by kspshnik** [comment]
> Задача 4. В чем некорректность ? Опишите проблемный кейс. Протестил, все работает.

@INextYP Это к тебе вопрос :))

**Comment by lexanikitin** [comment]
тогда мне простые вызовы мутатора , который уже написан ? 
body мутатору уходит всей сущности? всего user , или только свойство ?

**Comment by lexanikitin** [comment]
@kspshnik
@INextYP
Формат свойств пользователя не совпадает в JSONServer и в тестовых пользователях , которые были использованы во фронте на страницах requests. 
Какой формат эталонный ? 
Привожу requests к форматы который дает сервер ?

**Comment by kspshnik** [comment]
> тогда мне простые вызовы мутатора , который уже написан ? body мутатору уходит всей сущности? всего user , или только свойство ?

А, ты про это :)
Не, этот `api` никакую страницу не обслуживает, думаю он будет в итоге выпилен по результатам сопряжения.

**Comment by lexanikitin** [comment]
@kspshnik

мысль разовьешь ? задачу поставишь ?

**Comment by kspshnik** [comment]
> @kspshnik
> 
> мысль разовьешь ? задачу поставишь ?

Сама встанет на моменте сопряжения :)

**Comment by lexanikitin** [comment]
@kspshnik
ну т.е. таска закрыта ? 
ты меня выбил из колеи такими ответами ...

**Comment by FenixDeveloper** [comment]
@kspshnik @lexanikitin Ребята, а давайте не превращать диалоги пулл-реквеста в чаты. Если разработчик уточняет задачу, значит она поставлена недостаточно явно. Как минимум стоит детализировать либо по шагам, либо в образе ожидаемого результата что требуется сделать. Как вариант обсудить в чате изи на созвоне, так как комментарии к PR не место обсуждение, а место фиксации изменений и уточнений.
 
Со стороны же разработчика грамотно задавать вопрос тоже более развернуто чтобы подчеркнуть что какой-то анализ задачи был произведен и как вариант предположить тоже самое что предложено написать автору задачи, чтобы тот уже смог сказать то-ли требуется или нет.

@INextYP Помоги ребятам с формулированием задачи если она вообще нужна.
